### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets

### ISSUE THREAD

**Issue by K1LL3R234** [chkr1011/MQTTnet#1002]
I get errors like this when running ws with mqtt the connection id changes depends on error?
Any help?

info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
      Connection id "0HM3AG16SIDHK" communication error.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at MQTTnet.AspNetCore.MqttConnectionContext.<ReceivePacketAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.<ProcessSends>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.<DoSend>d__25.MoveNext()

**Comment by JanEggers** [comment]
its fine just set the loglevel of Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets to warning if that is bothering you.

you could also check that when the user leaves the site you close the websocket, but that will just lower the likelyness of these kind of messages.

**Comment by K1LL3R234** [comment]
Can you explain to me where I should do it or how?

**Comment by JanEggers** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1

**Comment by K1LL3R234** [comment]
Thank you very much
