### ISSUE TITLE
Issue while connection through proxy on linux arm 

### ISSUE THREAD

**Issue by Yuvaraja06** [chkr1011/MQTTnet#1007]
### Describe the bug
While using Proxy for connecting to MQTT server using Web Socket. Its working fine on Windows but on linux there is exception. 

### Which project is your bug related to?

MQTTnet.Exceptions.MqttCommunicationException: Unable to connect to the remote server
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.ComponentModel.Win32Exception (0x80090020): Unable to load shared library 'System.Net.Security.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSystem.Net.Security.Native: cannot open shared object file: No such file or directory
   at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credential)
   at System.Net.NTAuthentication.Initialize(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

### To Reproduce
1. Making connection to Websocket MQTT hosted on Azure using certificate validation
2. The request has to go through proxy server, so provided proxy details for the MQTT connection. 
3. Building application for linux arm and running it on linux board. Getting an exception on Communication failed event.  

### Additional context / logging
MQTTnet.Exceptions.MqttCommunicationException: Unable to connect to the remote server
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.ComponentModel.Win32Exception (0x80090020): Unable to load shared library 'System.Net.Security.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSystem.Net.Security.Native: cannot open shared object file: No such file or directory
   at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credential)
   at System.Net.NTAuthentication.Initialize(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
```
### Code example
 `options = new MqttClientOptionsBuilder()
                   .WithWebSocketServer(url)
                   .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V500)
                   //.WithCredentials(mQTTProxy.Username, mQTTProxy.Password)
                   .WithProxy(mQTTProxy.Address, mQTTProxy.Username, mQTTProxy.Password, mQTTProxy.Domain, mQTTProxy.BypassOnLocal, mQTTProxy.BypassList)
                   .WithTls(o =>
                   {
                       o.UseTls = true;
                       o.SslProtocol = System.Security.Authentication.SslProtocols.Tls;
                       o.CertificateValidationHandler = (MqttClientCertificateValidationCallbackContext g) =>
                       {
                           return true;
                       };
                       o.CertificateValidationCallback = (X509Certificate x, X509Chain y, SslPolicyErrors z, IMqttClientOptions d) =>
                       {
                       // TODO: Check conditions of certificate by using above parameters.
                       return true;
                       };
                       o.Certificates = new List<X509Certificate>()
                       {
                        new X509Certificate2(certificateDetails.CertificatePath, certificateDetails.KeyCertPath, X509KeyStorageFlags.Exportable)
                        };
                   }).Build();`
 
```csharp
\\ Put your code here.
```

**Comment by JanEggers** [comment]
we are using System.Net.WebSockets if they dont work its an issue for microsoft

**Comment by chkr1011** [comment]
I close this because I assume we cannot fix this issue on our own because it is a .net issue.
