### ISSUE TITLE
The client and server cannot communicate, because they do not possess a common algorithm

### ISSUE THREAD

**Issue by KMcNickel** [chkr1011/MQTTnet#1095]
### Describe your question
I recently shifted a project from .Net Core 3.1 to .Net 5.0 and updated MQTTNet to 3.0.14. Since making the change, I have been unable to use the MQTTNet client to connect to my Mosquitto broker. During the call to ConnectAsync, the code throws the exception: "The client and server cannot communicate, because they do not possess a common algorithm".

I am not sure why this is happening after the upgrade, one thought I had was to back the TLS version down to v1.2 instead of 1.3, but I get a remote certificate validation error (also new since the root for that certificate is in my Trusted Root Certificate Authority store and nothing on the other end changed)

I am running it on my (Windows) development computer, and have yet to try it on an Ubuntu box (same as the production server)

For reference, the MQTTClient options:
```
            List<X509Certificate> certs = new List<X509Certificate>
            {
                new X509Certificate2(config.GetValue<string>("DeviceCertificate"), config.GetValue<string>("CertificatePassword"))
            };
            IMqttClientOptions options = new MqttClientOptionsBuilder()
                .WithTcpServer("Server FQDN", 8883)
                .WithTls(new MqttClientOptionsBuilderTlsParameters
                {
                    UseTls = true,
                    Certificates = certs
                })
                .WithCleanSession()
                .Build();
```

The Mosquitto v2.0.7 config:
```
listener 1883 localhost

listener 8883
certfile /etc/mosquitto/certs/server.pem
capath /etc/mosquitto/ca_certificates/
keyfile /etc/mosquitto/certs/server_key.pem
require_certificate true
use_identity_as_username true
acl_file /etc/mosquitto/conf.d/aclfile

log_type all
log_timestamp_format %Y-%m-%dT%H:%M:%S

user mosquitto
```

### Which project is your question related to?

- Client

**Comment by KMcNickel** [comment]
In regards to TLSv1.2, it looks like theres an issue with it trying to connect to the revocation server which is odd since the server is running and the links are correct in the certificates, but is also an issue I can manage separately.

I still cannot seem to figure out why 1.3 doesn’t work but I would like to know if there is a way to find what algorithms are able to be / are actually being tried by the system and if there might be something else Im missing.

**Comment by SeppPenner** [comment]
That is strange. I had the same error and just downgraded the server to TLS1.2 explicitely in the options and the client as well, e.g.:

Client:
```csharp
var options = new MqttClientOptionsBuilder()
    .WithClientId("ClientId")
    .WithTcpServer("mybroker.com", 8883)
    .WithCredentials("Username", "Password")
    .WithTls(new MqttClientOptionsBuilderTlsParameters()
    {
        UseTls = true,
        SslProtocol = SslProtocols.Tls12
    })
    .WithCleanSession()
    .Build();
var factory = new MqttFactory();
var mqttClient = factory.CreateMqttClient();
await mqttClient.ConnectAsync(options);
```

Server:
```csharp
var optionsBuilder = new MqttServerOptionsBuilder().WithDefaultEndpoint()
    .WithEncryptedEndpoint().WithEncryptedEndpointPort(8883)
    .WithEncryptionSslProtocol(SslProtocols.Tls12);
var mqttServer = new MqttFactory().CreateMqttServer();
await mqttServer.StartAsync(optionsBuilder.Build());
```

(Of course some more logic like adding certificates, if needed).

But this worked for me...

**Comment by vukovinski** [comment]
Happened to me also, but when changed to Tls12, I'm getting a different error:

```
Authentication failed because the remote party has closed the transport stream.
```

Still investigating. Note that I'm using .Net Core 3.1.

**Comment by vukovinski** [comment]
So I was trying to use TLS with credentials only. Works when toggling TLS off. Will test later with certificates and TLS.

**Comment by amelkor** [comment]
Faced the same issue with TLS1.3, was following this [doc](https://github.com/chkr1011/MQTTnet/wiki/Server#using-a-certificate)
Switching to TLS1.2 works fine
The server code the same as there, client's one below:
```
var tlsOptions = new MqttClientOptionsBuilderTlsParameters
{
    UseTls = true,
    SslProtocol = SslProtocols.Tls13,
    AllowUntrustedCertificates = true,
    IgnoreCertificateChainErrors = true,
    IgnoreCertificateRevocationErrors = true,
};
_options = new MqttClientOptionsBuilder()
    .WithTcpServer("localhost", 8883)
    .WithClientId("some_id")
    .WithCredentials("login", "pass")
    .WithProtocolVersion(MqttProtocolVersion.V500)
    .WithTls(tlsOptions)
    .Build();
```
getting this:

```
MQTTnet.Exceptions.MqttCommunicationException: The client and server cannot communicate, because they do not possess a common algorithm.
 ---> System.ComponentModel.Win32Exception (0x80090331): The client and server cannot communicate, because they do not possess a common algorithm.
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

**Comment by vukovinski** [comment]
This is probably due to TLS 1.2 -> TLS 1.3 changes.

https://www.microsoft.com/security/blog/2020/08/20/taking-transport-layer-security-tls-to-the-next-level-with-tls-1-3/

**Comment by SeppPenner** [comment]
@amelkor That's correct since you're using `SslProtocol = SslProtocols.Tls13,` with the client and `.WithEncryptionSslProtocol(SslProtocols.Tls12)` with the server (Following the doc under https://github.com/chkr1011/MQTTnet/wiki/Server#using-a-certificate). There is a TLS mismatch.

If you follow my code above (https://github.com/chkr1011/MQTTnet/issues/1095#issuecomment-788071245), this should work properly...

**Comment by DeepakBasavarajappa** [comment]
Recently I faced this issue. The thing that was missing in my case was that devbox from which I was making Http requests did not have TLS1.3 enable in the OS and also TLS supporting ciphers suites were also not enabled. After enabling them the issue is resolved. 

I followed below blogs to 
1. Enable TLS1.3  https://thesecmaster.com/blog/how-to-enable-tls-1-3-on-windows-server-2022
2. Enable cipher suites : https://michaelhowardsecure.blog/
