### ISSUE TITLE
Upgrade to 3.0.14 TLS issue

### ISSUE THREAD

**Issue by chrisdrobison** [chkr1011/MQTTnet#1099]
### Describe the bug
I recently upgraded from 3.0.13 to 3.0.14 and it appears there are some issues with connecting to GCP Core IoT over TLS. These errors are occurring on MacOS BigSur and I'm targeting .NET Core 3.1. The following is the managed client configuration that worked with 3.0.13. 

```csharp
_logger.LogInformation($"Connecting to MQTT as {ClientId}");
var options = new ManagedMqttClientOptionsBuilder()
    .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
    .WithClientOptions(new MqttClientOptionsBuilder()
        .WithClientId(ClientId)
        .WithCredentials(this)
        .WithTcpServer(_lookConfig.CurrentValue.MqttHost, _lookConfig.CurrentValue.MqttPort)
        .WithProtocolVersion(MqttProtocolVersion.V311)
        .WithKeepAlivePeriod(Constants.KeepAlive)
        .WithTls()
        .Build())
    .Build();

_client.UseConnectedHandler(async args =>
{
    await _client.SubscribeAsync(ConfigTopic, MqttQualityOfServiceLevel.AtLeastOnce);
    await _client.SubscribeAsync(CommandsTopicSubscription, MqttQualityOfServiceLevel.AtMostOnce);
});

```
When I upgrade to 3.0.14 and run with that exact configuration, I receive the following error:

```
MQTTnet.Exceptions.MqttCommunicationException: Authentication failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.PlatformNotSupportedException: The requested security protocol is not supported.
   at System.Net.SafeDeleteSslContext.SetProtocols(SafeSslHandle sslContext, SslProtocols protocols)
   at System.Net.SafeDeleteSslContext.CreateSslContext(SafeFreeSslCredentials credential, Boolean isServer)
   at System.Net.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapAndThrowException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)

```
When I update the `.WithTls()` to the following:

```csharp
.WithTls(config => config.SslProtocol = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13)
```
And then run, I get the following error:
```
MQTTnet.Exceptions.MqttProtocolViolationException: Expected at least 258 bytes but there are only 3 bytes
   at MQTTnet.Formatter.MqttPacketBodyReader.ReadSegmentWithLengthPrefix()
   at MQTTnet.Formatter.MqttPacketBodyReader.ReadStringWithLengthPrefix()
   at MQTTnet.Formatter.V3.MqttV310PacketFormatter.DecodeConnectPacket(IMqttPacketBodyReader body)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.TryReceivePacketsAsync(CancellationToken cancellationToken)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.WaitOneAsync(TimeSpan timeout)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.AuthenticateAsync(IMqttChannelAdapter channelAdapter, MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)

```

### Which project is your bug related to?

- ManagedClient

**Comment by chrisdrobison** [comment]
The upgrade works fine when I run it on Ubuntu, so this maybe appears to be Mac specific.

**Comment by chkr1011** [comment]
@chrisdrobison To me looks like a .net issue. The Stack Trace contains _System.PlatformNotSupportedException: The requested security protocol is not supported._ which indicates that this protocol is not supported on macOS. If this was removed from .net etc. is not part of this project because we only use .net here.

**Comment by chrisdrobison** [comment]
Perfect. I’d just thought I’d post this just in case someone hits it in the future.

**Comment by msavara** [comment]
Hello, can anybody tell me what is fix for this issue ?

**Comment by SeppPenner** [comment]
Maybe downgrade to TLS1.2 as described in https://github.com/chkr1011/MQTTnet/issues/1085#issuecomment-788067211.
