### ISSUE TITLE
net 5 MQTTnet.Exceptions.MqttCommunicationException: Authentication failed The problem remains

### ISSUE THREAD

**Issue by pigwing** [chkr1011/MQTTnet#1113]
version 3.0.15

### Which project is your bug related to?
- ManagedClient
#1098 

MQTTnet.Exceptions.MqttCommunicationException: Authentication failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapAndThrowException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
>> [2021-03-05T09:30:53.9877502Z] [4] [MqttClient] [Verbose]: Disconnecting [Timeout=00:00:10]
>> [2021-03-05T09:30:53.9924739Z] [4] [MqttClient] [Verbose]: Disconnected from adapter.
>> [2021-03-05T09:30:53.9980608Z] [4] [MqttClient] [Info]: Disconnected.
[17:30:54 Error] ECO.Quartz.Jobs.RecordValuePushJob
Authentication failed, see inner exception.

**Comment by chkr1011** [comment]
this is a .net issue. Probably they removed support for older TLS protocols. This is nothing this library can fix. You may need to downgrade to .net core 3.1 etc. in order to get it working.

**Comment by SeppPenner** [comment]
Or you need to upgrade your server and client code to use TLS >= 1.2 depending on how variable you are there. Example for the client side (Using TLS1.2) can be found here: https://github.com/chkr1011/MQTTnet/issues/1085#issuecomment-788067211.

**Comment by pigwing** [comment]
oh sorry i see thx
