### ISSUE TITLE
MqttCommunicationTimedOutException when connecting

### ISSUE THREAD

**Issue by imarcu** [chkr1011/MQTTnet#1140]
### Describe the bug
Attempting to connect to a Mqttnet server with the default client and receiving a timeout

### Which project is your bug related to?

- Client
- Server

### To Reproduce
.Net 5 web app with the following code
server
```
ConfigureServices
services.AddHostedMqttServer(mqttServer => 
                    mqttServer.WithoutDefaultEndpoint()
                        .WithDefaultEndpointPort(5001).WithEncryptionCertificate(
                            X509Certificate2.CreateFromPemFile(
                                "server.crt",
                                "server.key")))
                .AddMqttConnectionHandler()
                .AddConnections(options => options.DisconnectTimeout = TimeSpan.FromMinutes(1));

Configure
 app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapConnectionHandler<MqttConnectionHandler>(
                    "/mqtt",
                    httpConnectionDispatcherOptions => httpConnectionDispatcherOptions.WebSockets.SubProtocolSelector =
                        protocolList =>
                            protocolList.FirstOrDefault() ?? string.Empty);
            });

         
            app.UseMqttServer(server =>
            {
                server.UseClientConnectedHandler(args => Console.WriteLine($"Client connected with id {args.ClientId}"));
                server.UseClientConnectedHandler(args => Console.WriteLine($"Client disconnected with id {args.ClientId}"));
                server.UseApplicationMessageReceivedHandler(args =>
                    Console.WriteLine(
                        $"Message received on Mqtt broker with {args.ClientId} + {args.ApplicationMessage.Topic} + {args.ApplicationMessage.Payload}"));
            });
```
client

```
public static void StartClient(string clientId)
        {
           Task.Delay(TimeSpan.FromSeconds(10)).ContinueWith((async task =>
           {
               Client.Instance.UseConnectedHandler(e =>
               {
                   Console.WriteLine("### CONNECTED WITH SERVER ###");
               });
               Client.Instance.UseDisconnectedHandler(e =>
               {
                   Console.WriteLine($"Disconnected from broker + {e.Reason} + {e.Exception} + {e.Exception?.InnerException}+ {e.AuthenticateResult} + {e.ReasonCode}");
               });
               Client.Instance.UseApplicationMessageReceivedHandler(e =>
               {
                   var payload = Encoding.UTF8.GetString(e.ApplicationMessage.Payload);
                   Console.WriteLine($"### {clientId}  RECEIVED APPLICATION MESSAGE ###");
                   Console.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
                   Console.WriteLine($"+ Payload = {payload}");
                   Console.WriteLine();

               });

               //if (Client.Instance.IsConnected)
               //    Client.Instance.DisconnectAsync();
               Console.WriteLine("Starting MQTT Client");
               var connectResult = await Client.Instance.ConnectAsync(
                   new MqttClientOptionsBuilder().WithClientId(clientId)
                       .WithTcpServer("localhost", 5001)
                       .WithTls(options =>
                       {
                           options.Certificates = new[]
                               {X509Certificate.CreateFromCertFile("ca.crt")};
                           options.AllowUntrustedCertificates = true;
                       })
                       .WithKeepAlivePeriod(TimeSpan.FromSeconds(60))
                       .Build());
               Console.WriteLine("Connected");
           }));
        }
```
### Expected behavior
Unsure why it times out. The same certificates work with a mosquittoo server/client sample

Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__50`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<AuthenticateAsync>d__44.MoveNext()

**Comment by imarcu** [comment]
Adding Extra logs:
> [2021-04-09T17:49:26.7072151Z] [11] [MqttTcpServerListener] [Verbose]: Client '192.168.1.10:50412' accepted by TCP listener '0.0.0.0:8883, ipv4'.
>> [2021-04-09T17:49:26.7093734Z] [11] [MqttTcpServerListener] [Error]: Error while handling client connection.
System.ComponentModel.Win32Exception (0x8009030E): No credentials are available in the security package
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at MQTTnet.Implementations.MqttTcpServerListener.TryHandleClientConnectionAsync(CrossPlatformSocket clientSocket)
>> [2021-04-09T17:49:26.7407207Z] [11] [MqttTcpServerListener] [Verbose]: Client '192.168.1.10:50412' disconnected at TCP listener '0.0.0.0:8883, ipv4'.

**Comment by imarcu** [comment]
After further investigation i think the issue may be around this line of code https://github.com/chkr1011/MQTTnet/blob/77338527b497bd7ae18bf0abb4e0088eaf09ac39/Source/MQTTnet/Implementations/MqttTcpServerListener.cs#L162


Based on the following windows issue I think Windows has in issue with the way certificates are loaded and then passed to the SSL stream:
https://github.com/dotnet/runtime/issues/23749#issue-558282199
https://github.com/dotnet/runtime/issues/27826

Can you validate this issue and provide a workaround?

**Comment by pver** [comment]
@imarcu not sure if you're still looking for an answer to this. I've seen similar issues with .net core and used the following workaround method to get the certificate working:

```
        public X509Certificate2 CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
        {
            var certificateWithPrivateKey = certificate.CopyWithPrivateKey(privateKey);

            // .Net core on windows needs this extra export as pfx type to work properly with the X509Certificate2:
            // See: https://github.com/dotnet/runtime/issues/23749#issuecomment-388231655
            var pfxExported = certificateWithPrivateKey.Export(X509ContentType.Pfx);

            return new X509Certificate2(pfxExported);
        }
```
(so basically copy the private key into the certificate, and do an extra export of the certificate indicating pfx as export type)
