### ISSUE TITLE
Connect fail with tls certificate in version v3.0.16, I guess the problem is pre-handling at TLS certificate... 

### ISSUE THREAD

**Issue by jamwu1991** [chkr1011/MQTTnet#1207]
### Which project is your question related to?
- Client
- ManagedClient

### Describe your question
-MQTTnet Version -> v3.0.16
-MQTT.ManagedClient -> v3.0.16

----Question Description----

I need to use TLS to connect mqtt broker by MQTTNet. I encountered "mqttClient.IsConnected = false" after call mqttClient.ConnectAsync(). And the exception is shown off the message "The client is not connected." after call mqttClient.PublishAsync(). 

I already try to connect same host with same parameter by credential is work. I guess the problem is the pre-handling method at 
TLS certificate. The mqttClient.ConnectAsync will make different result after different pre-handling method.

I have 5 file and description at following: 
ca.crt -> Just a ca certificate
client.crt -> Just a client certificate
client.key -> Just a client key
clientTwoPwd12345.pfx -> combine client crt and client key with password 12345
using cmd：`openssl pkcs12 -export -out clientTwoPwd12345.pfx -in client.crt -inkey client.key`
clientThreeWithCaCrtPwd12345.pfx -> combine client crt ,client key and ca.crt with password 12345
using cmd：`openssl pkcs12 -export -out clientThreeWithCaCrtPwd12345.pfx -in client.crt -inkey client.key -certfile ca.crt`

Can coding god tell me how to using these file to make connect broker success?  I already try 8 way to connect but all fail to connect. If code have any error or any suggest, please tell me with free. 

Thanks every god to look this issue and thanks for you any help and suggest. 

Code is following：

```
public void MQTTConnect()
        {
            Connect();
            Publish();
        }

        public void Connect()
        {
            DirectoryInfo dir = Directory.GetParent(Environment.CurrentDirectory).Parent.Parent;

            string caCertPath = dir.FullName + @"\certs\ca.crt";
            string clientCertPath = dir.FullName + @"\certs\client.crt";
            string clientKeyPath = dir.FullName + @"\certs\client.key";
            string clientTwoPwd12345PFXPath = dir.FullName + @"\certs\clientTwoPwd12345.pfx";
            string clientThreeWithCaCrtPwd12345PFXPath = dir.FullName + @"\certs\clientThreeWithCaCrtPwd12345.pfx";

            var caCert = X509Certificate.CreateFromCertFile(caCertPath);
            var clientCert = new X509Certificate2(clientCertPath, clientKeyPath);
            var clientCertWithFlag = new X509Certificate2(clientCertPath, clientKeyPath, X509KeyStorageFlags.Exportable);
            var clientTwoPwd12345PFX = new X509Certificate2(clientTwoPwd12345PFXPath, "12345");
            var clientThreeWithCaCrtPwd12345PFX = new X509Certificate2(clientThreeWithCaCrtPwd12345PFXPath, "12345");

            var factory = new MqttFactory();
            mqttClient = factory.CreateMqttClient();

            var tlsParameters = new MqttClientOptionsBuilderTlsParameters
            {
                UseTls = true,
                Certificates = new List<X509Certificate> { caCert, clientCert }, //try1
                //Certificates = new List<X509Certificate> { caCert, clientCertWithFlag }, //try2
                //Certificates = new List<X509Certificate> { caCert, clientTwoPwd12345PFX }, //try3
                //Certificates = new List<X509Certificate> { caCert, clientThreeWithCaCrtPwd12345PFX }, //try4
                //Certificates = new List<X509Certificate> { clientCert }, //try5
                //Certificates = new List<X509Certificate> { clientCertWithFlag }, //try6
                //Certificates = new List<X509Certificate> { clientTwoPwd12345PFX }, //try7
                //Certificates = new List<X509Certificate> { clientThreeWithCaCrtPwd12345PFX }, //try8
                IgnoreCertificateRevocationErrors = true,
                IgnoreCertificateChainErrors = true,
                AllowUntrustedCertificates = true,
                SslProtocol = System.Security.Authentication.SslProtocols.Tls12
            };

            //The connectOptions  can connect success
            /*var connectOptions = new MqttClientOptionsBuilder()
                .WithKeepAlivePeriod(new TimeSpan(0, 0, 0, 0, Timeout.Infinite))
                .WithClientId("test0002")
                .WithTcpServer(host, 1883)
                .WithCredentials(useName, "")
                .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V311)
                .WithCleanSession()
                .Build();*/

            var connectOptions = new MqttClientOptionsBuilder()
                .WithKeepAlivePeriod(new TimeSpan(0, 0, 0, 0, Timeout.Infinite))
                .WithClientId("test0001")
                .WithTcpServer(host, 8883)
                .WithTls(tlsParameters)
                .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V311)
                .WithCleanSession()
                .Build();

            var result = mqttClient.ConnectAsync(connectOptions);

            Thread.Sleep(1000); //Wait response from connect result
            Debug.WriteLine("Try connect result is ："　+ mqttClient.IsConnected);
        }

        public void Publish()
        {
            var microCT_IoT_Parameter = new MicroCT_IoT_Parameter
            {
                /*Json Message*/
            };

            string jsonString = JsonConvert.SerializeObject(microCT_IoT_Parameter);

            try
            {
                var message = new MqttApplicationMessageBuilder()
                .WithTopic(topic)
                .WithPayload(jsonString)
                .WithExactlyOnceQoS()
                .WithRetainFlag(true)
                .Build();

                mqttClient.PublishAsync(message);
            }
            catch (Exception ex)
            {
                Debug.WriteLine("----------------------");
                Debug.WriteLine("Publish~：" + ex);
                Debug.WriteLine("----------------------");
            }
            finally
            {

            }
        }
```

Exception is following：
```
Try connect result is ：False
'MQTTJ0729_VS2015.vshost.exe' (CLR v4.0.30319: MQTTJ0729_VS2015.vshost.exe): Loaded 'C:\Disk D\MQTTJ0802_VS2015\MQTTJ0729_VS2015\MQTTJ0729_VS2015\bin\Debug\Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MQTTJ0729_VS2015.vshost.exe' (CLR v4.0.30319: MQTTJ0729_VS2015.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MQTTJ0729_VS2015.vshost.exe' (CLR v4.0.30319: MQTTJ0729_VS2015.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationException' in MQTTnet.dll
----------------------
Publish~：MQTTnet.Exceptions.MqttCommunicationException: The client is not connected.
   於 MQTTnet.Client.MqttClient.ThrowIfNotConnected()
   於 MQTTnet.Client.MqttClient.PublishAsync(MqttApplicationMessage applicationMessage, CancellationToken cancellationToken)
   於 MQTTnet.Client.MqttClientExtensions.PublishAsync(IMqttClient client, MqttApplicationMessage applicationMessage)
   於 MQTTJ0729_VS2015.Form1.Publish() 於 C:\Disk D\MQTTJ0802_VS2015\MQTTJ0729_VS2015\MQTTJ0729_VS2015\Form1.cs: 行 106
----------------------
```

**Comment by andyesys** [comment]
Same problem here:

```
      [2021-08-30T15:29:21.0656169Z] [] [12] [MqttClient] [Error]: Error while connecting with server.
      MQTTnet.Exceptions.MqttCommunicationException: Der Client und der Server können keine Daten austauschen, da sie nicht über einen gemeinsamen Algorithmus verfügen.
       ---> System.ComponentModel.Win32Exception (0x80090331): Der Client und der Server können keine Daten austauschen, da sie nicht über einen gemeinsamen Algorithmus verfügen.
         at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
         at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
         at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
         at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
         at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
         at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
         at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
         at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
         at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
         at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
         at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
         at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
         at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at MQTTnet.Adapter.MqttChannelAdapter.WrapAndThrowException(Exception exception)
         at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
         at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
```

**Comment by SeppPenner** [comment]
This is due to a change in .Net (Switch to TLS1.3 by default now)... You need to downgrade TLS manually like so:

```csharp
.WithTls(new MqttClientOptionsBuilderTlsParameters()
        {
            UseTls = true,
            SslProtocol = System.Security.Authentication.SslProtocols.Tls12
        })
```
