### ISSUE TITLE
Unobserved exception

### ISSUE THREAD

**Issue by GieltjE** [chkr1011/MQTTnet#161]
Broker: Mosquitto v1.4.14
MQTTnet: v2.6.0

Both the connection and server are stable but exceptions like these happen alot.

```There are no context policies.

 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Client.MqttPacketDispatcher.<WaitForPacketAsync>d__4.MoveNext()

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

---> (Inner Exception #0) MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Client.MqttPacketDispatcher.<WaitForPacketAsync>d__4.MoveNext()<---
```

**Comment by chkr1011** [comment]
Hi @GieltjE,
thanks for sharing this issue.

@JanEggers This code is coming from the TimeoutAfter extension method. I had a look and to me it seems that the original task is no longer maintained if the timeout has occured. Then the exception will be not observed. Do you have an idea how to solve this in the TimeoutAfter method? Another solution would be checking every method which calls _TimeoutAfter_ and ensuring that it will handle exceptions on its own. 

Best regards
Christian

**Comment by JanEggers** [comment]
hi 

@GieltjE can you please provide the complete callstack. for me it looks like you dont await a PublishAsync call.

I dont think this is a issue in the library as we always await tasks. if it was a library error this exception whould pop every time there is a communication timeout. and these tests https://github.com/chkr1011/MQTTnet/blob/312773d0549c5bd2b01881de8841ba6c6258d599/Tests/MQTTnet.Core.Tests/ExtensionTests.cs#L13-L25 veryfy that we get a MqttCommunicationTimeoutException but op had a AggregateException in the finalizer.

**Comment by GieltjE** [comment]
Indeed I don't await some PublishAsync calls (but do have an continuewith on them), don't seem to have fully grasped the whole async/await bits yet.

**Comment by GieltjE** [comment]
Wasn't the whole point of async that one shouldn't have to wait?

**Comment by GieltjE** [comment]
Am now awaiting all calls, now I get two different exceptions.

Code example:
```            Task task = MqttClient.PublishAsync(new MqttApplicationMessage { QualityOfServiceLevel = MqttQualityOfServiceLevel.ExactlyOnce, Topic = topic, Retain = false, Payload = message });
            task.ContinueWith(t => HandleExceptionAndRequeueItem(message, topic), TaskContinuationOptions.OnlyOnFaulted);
            task.Wait();```

```MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Client.MqttPacketDispatcher.<WaitForPacketAsync>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__37`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Client.MqttClient.<PublishAsync>d__26.MoveNext()```

**Comment by JanEggers** [comment]
if you dont want to wait you can await. (that does not block the current thread)
Anyway you have timeouts, i dont know how to dig deeper. @chkr1011 can you catch and rethrow the exception in MqttPacketDispatcher so you can add a messageid or any other detail lik timestams that helps to find the issue. With that info you could look in wireshark but without you will never find the issue i guess.

**Comment by GieltjE** [comment]
How can I at least catch these damn exceptions without crashing the whole app?

**Comment by JanEggers** [comment]
try 
{
   await client.Publish(....)
}
catch(ex)

**Comment by GieltjE** [comment]
Also considering that await blocks waits for the code to be executed it is still waiting (even though not blocking the thread, the code below still has to wait before being executed).

**Comment by JanEggers** [comment]
yup

**Comment by GieltjE** [comment]
So even though everything is asynchronous we still have to wait for every message to be processed before inserting the next?

**Comment by JanEggers** [comment]
nope you can publish an array of Messages, or if you simply whant to fire and forget you can wrap publish with an async void method that handles the exception. but thats not good practise

**Comment by GieltjE** [comment]
Still getting the first exception even though everting is awaited within a try/catch.

**Comment by GieltjE** [comment]
Edit, seem to have vanished.

**Comment by GieltjE** [comment]
It can be triggered by simply restarting the mqtt server a few times when a connection is open.

**Comment by chkr1011** [comment]
Hi,
please test this again with version 2.7.3. Several connection handling issues are fixed in this version.
Best regards
Christian

**Comment by GieltjE** [comment]
Will do, thanks for the effort.

**Comment by GieltjE** [comment]
``` System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Client.MqttPacketDispatcher.<WaitForPacketAsync>d__3.MoveNext()

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

---> (Inner Exception #0) MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Client.MqttPacketDispatcher.<WaitForPacketAsync>d__3.MoveNext()<---```

**Comment by GieltjE** [comment]
I have it boiled down fairly consistent reproducable situation in VS2017, I could remove the dll and load the source if that would help.

**Comment by chkr1011** [comment]
Yes please provide some more details. Do you have a snipped which causes this issue? I need to test this on my own machine.

**Comment by GieltjE** [comment]
```
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext() in X:\FYN Retail\ClassLibrary1\Internal\TaskExtensions.cs:line 56

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Client.MqttPacketDispatcher.<WaitForPacketAsync>d__3.MoveNext() in X:\FYN Retail\ClassLibrary1\Client\MqttPacketDispatcher.cs:line 31

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

---> (Inner Exception #0) MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext() in X:\FYN Retail\ClassLibrary1\Internal\TaskExtensions.cs:line 56

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Client.MqttPacketDispatcher.<WaitForPacketAsync>d__3.MoveNext() in X:\FYN Retail\ClassLibrary1\Client\MqttPacketDispatcher.cs:line 31<---
```

**Comment by GieltjE** [comment]
Recently a new exception has started appearing:

```Name:Retail.exe

There are no context policies.

 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.

   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)

   at MQTTnet.Client.MqttPacketDispatcher.<>c__DisplayClass2_0.<Dispatch>b__0()

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

---> (Inner Exception #0) System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.

   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)

   at MQTTnet.Client.MqttPacketDispatcher.<>c__DisplayClass2_0.<Dispatch>b__0()

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()<---
````

**Comment by GieltjE** [comment]
It seems that the whole of Client\MqttPacketDispatcher.cs is missing the proper task exception handling, the latest patches in develop branch made things much worse for this problem.

Also why is "awaiter.SetResult(packet);" called twice, once within the Task.Run on line 36 and once on line 35.

@chkr1011 please let me know if I can help run some tests, this bug is really starting to annoy me.

**Comment by GieltjE** [comment]
Probably fixed with the latests commits in development, thanks for the effort.
