### ISSUE TITLE
Version 2.6.0 not working on Arm Device?

### ISSUE THREAD

**Issue by Zuendelmeister** [chkr1011/MQTTnet#168]
Hi again,

I have a problem using the new MQTTNet.dll on my arm device. 
I get the following Exception:
`
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'MQTTnet, Version=2.6.0.0, Culture=neutral, PublicKeyToken=909d71c7                                                                                 24771999'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at MqttClientModule.MqttClientModule.threadBodyAsync()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`
 I used the dll out of this folder:
C:\Users\<USERNAME>\.nuget\packages\mqttnet\2.6.0\lib\netstandard1.3

I also tried to use the  build.ps1 script but this throws errors:
Die Schlüsseldatei ist möglicherweise kennwortgeschützt => "The keyfile is possibly password protected
.\NuGet.exe : Fehlender Optionswert für: "-Version" => NuGet.exe: missing optionvalue for "-Version"

Is it because of my arm device or how can I resolve this?
Thanks =)

Best regards,
Zuendelmeister

**Comment by Zuendelmeister** [comment]
I found the the problem. The dll has to be in the dotnet/shared/Microsoft.NETCore.App/<VERSION>/ folder. My mistake.
