### ISSUE TITLE
Connection Issue - Timeout while waiting for packet of type 'MqttConnAckPacket'.

### ISSUE THREAD

**Issue by mishrashash** [chkr1011/MQTTnet#195]
First of all many thanks for such a great library! 

While using managed client I'm getting an exception where MqttConnAckPacket is not being received. It works for some brokers but for one of the broker this error is present all the time. Here is the log:

`>> [2018-03-09T18:54:44.7795313+05:30] [23] [ManagedMqttClient] [Info]: Stopped
>> [2018-03-09T18:54:44.7795313+05:30] [23] [ManagedMqttClient] [Info]: Stopped
>> [2018-03-09T18:55:18.4460470+05:30] [30] [MqttPacketDispatcher] [Warning]: Timeout while waiting for packet of type 'MqttConnAckPacket'.
>> [2018-03-09T18:55:18.4460470+05:30] [30] [MqttPacketDispatcher] [Warning]: Timeout while waiting for packet of type 'MqttConnAckPacket'.
>> [2018-03-09T18:55:18.5905630+05:30] [30] [MqttClient] [Error]: Error while connecting with server.
MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttPacketDispatcher.<WaitForPacketAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__37`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<AuthenticateAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__22.MoveNext()
>> [2018-03-09T18:55:18.5905630+05:30] [30] [MqttClient] [Error]: Error while connecting with server.
MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttPacketDispatcher.<WaitForPacketAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__37`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<AuthenticateAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__22.MoveNext()
>> [2018-03-09T18:55:18.7260856+05:30] [30] [ManagedMqttClient] [Info]: Stopped`

Both Communication Timeout and Keep Alive Period are set to 60secs.

I can connect to the same broker using MQTT.fx with exactly same settings.

**Comment by mishrashash** [comment]
Tried Wireshark and the ACK is actually being received but somehow library is ignoring it? Any idea?

**Comment by chkr1011** [comment]
Hi @mishrashash,
thanks for sharing this issue. Please provide some more details about the not working broker. And please share the Wireshark export here so I can debug the messages directly. Maybe this is a version issue? 

Best regards
Christian

**Comment by mishrashash** [comment]
Hey @chkr1011,

Thanks for the comment. I don't have hold of the same broker now  but should get it fairly soon. As  soon as I  get it I'll provide you the Wireshark session export for you to debug.

I tried with version 2.6, 2.7 and the RC release but got same issue with all so doesn't look like it's a version issue.

FYI: I managed to work against same broker using paho.mqtt3.c (https://github.com/eclipse/paho.mqtt.c) wrapper for .NET: https://github.com/xljiulang/Paho.MqttDotnet

**Comment by nowakpiotr** [comment]
While using managed client I'm getting an exception where MqttConnAckPacket is not being received as well.I can not say what is causing this, but I will try to find it.

**Comment by chkr1011** [comment]
Please post the export of the Wirehsark trace containing the ACK packet. Then I can debug it.
Another relevant info is the broker you use and the used MQTT protocol version.

**Comment by nowakpiotr** [comment]
Now when I started test under Rider:
Unhandled Exception: MQTTnet.Exceptions.MqttCommunicationException: The WebSocket is in an invalid state ('CloseSent') for this operation. Valid states are: 'Open, CloseReceived' ---> System.Net.WebSockets.WebSocketException: The WebSocket is in an invalid state ('CloseSent') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.WinHttpWebSocketState.InterlockedCheckValidStates(WebSocketState[] validStates)
   at System.Net.WebSockets.WinHttpWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at System.Net.WebSockets.ClientWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at MQTTnet.Implementations.WebSocketStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\Users\pnow\Documents\GIT\Private\cumulocity-sdk-cs\externals\MQTTnet\Frameworks\MQTTnet.NetStandard\Implementations\WebSocketStream.cs:line 100
   at MQTTnet.Adapter.MqttChannelAdapter.<>c__DisplayClass11_0.<<SendPacketsAsync>b__0>d.MoveNext() in C:\Users\pnow\Documents\GIT\Private\cumulocity-sdk-cs\externals\MQTTnet\Frameworks\MQTTnet.NetStandard\Adapter\MqttChannelAdapter.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__14.MoveNext() in C:\Users\pnow\Documents\GIT\Private\cumulocity-sdk-cs\externals\MQTTnet\Frameworks\MQTTnet.NetStandard\Adapter\MqttChannelAdapter.cs:line 173
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__14.MoveNext() in C:\Users\pnow\Documents\GIT\Private\cumulocity-sdk-cs\externals\MQTTnet\Frameworks\MQTTnet.NetStandard\Adapter\MqttChannelAdapter.cs:line 214
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__37`1.MoveNext() in C:\Users\pnow\Documents\GIT\Private\cumulocity-sdk-cs\externals\MQTTnet\Frameworks\MQTTnet.NetStandard\Client\MqttClient.cs:line 339
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Client.MqttClient.<SubscribeAsync>d__24.MoveNext() in C:\Users\pnow\Documents\GIT\Private\cumulocity-sdk-cs\externals\MQTTnet\Frameworks\MQTTnet.NetStandard\Client\MqttClient.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Cumulocity.MQTT.Client.<<SubscribeEvt>b__90_0>d.MoveNext() in C:\Users\pnow\Documents\GIT\Private\cumulocity-sdk-cs\src\MQTT.Client.NetStandard\Client.cs:line 436
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by russd2357** [comment]
Hi,  I'm getting the same issue using the MqttClient connecting to a cloudmqtt.com broker. Odd thing is it works on a shared instance,  but not their dedicated one.

**Comment by chkr1011** [comment]
@russd2357 I also use CloudMqtt with this library and have no issues. What is the difference at the dedicated one. Do you have some details?

**Comment by chkr1011** [comment]
Hi,
I released 2.8.0-alpha5. Please let me know if this version now works better.
Best regards
Christian

**Comment by russd2357** [comment]
Hi Christian,

I migrated the app to .NET Standard 2 and used version 2.7.5. It meant
sacrificing support for Android 7 but we have a responsive web app that can
take care of that.

Feel free to close the issue.

Thanks again for providing this library!

Russell
