### ISSUE TITLE
Client disconnections/reconnections on raspberry pi

### ISSUE THREAD

**Issue by SNival** [chkr1011/MQTTnet#222]
Hi,

I'm having troubles with the version 2.7.4 of the library.

I have 2 background process on a RPi 3, running Windows 10 IOT Core 10.0.16299.371 : 
a server, based on sample in the wiki
and a managed client, also based on wiki, with a 10 seconds keep alive and a few subscriptions.
The messages are well sent and received, but the client regularly disconnects from the server, then reconnects within 1 or 2 seconds.

The exceptions in the client Disconnected event are sometimes "MqttConnectionTimedOutException", sometimes socket exception "An existing connection was forcibly closed by the remote host", some TaskCanceledException...

The problem doesn't occur on a desktop Windows 10, nor when connecting to cloud EMQTT server.

Apart from that little problem, the library works very well (publishin and receiveing messages, auto reconnection) and fits our project perfectly :-)

I may send you the source of the little applicationsand/or the log from the server.

Best regards

**Comment by chkr1011** [comment]
Hi,
thanks for reporting this issue. I am working on some UWP issues at the moment. Probably your issue is then fixed. Please still share some code for me to reproduce.
Best regards
Christian

**Comment by SNival** [comment]
Hi Christian,

Once again, thank you for the library and your support !
While trying to extract the smallest possible code, I was not able to reproduce the problem. Maybe the problem is related to the load on the PI (even if I barely reach peaks at 25% CPU).
Anyway, I added trace in both the client and the server, using the MqttNetGlobalLogger.LogMessagePublished event and doing so, i had no disconnections anymore...
Adding trace in the client or the server only reactivates disconnections.
I join the log files, the server source and the configuration of the client, hoping it may help.

Best regards,

Stéphane
[Logs and configs.zip](https://github.com/chkr1011/MQTTnet/files/1938476/Logs.and.configs.zip)

**Comment by SNival** [comment]
Just tried with the new version, unfortunately it doesn't connect at all...

Here is the log :

```
SRV>> 10:16:22.028 Started. (Info, MqttServer/2)
SRV > Started
CLT>> 10:16:22.908 Started (Info, ManagedMqttClient/3)
CLT>> 10:16:23.069 Trying to connect with server. (Verbose, MqttClient/4)
CLT>> 10:16:23.081 Connecting [Timeout=00:00:30] (Verbose, MqttChannelAdapter/4)
CLT>> 10:16:25.265 Connection with server established. (Verbose, MqttClient/7)
CLT>> 10:16:25.294 Start receiving packets. (Verbose, MqttClient/4)
CLT>> 10:16:25.364 TX >>> Connect: [ClientId=UiClient] [Username=] [Password=] [KeepAlivePeriod=10] [CleanSession=True] [Timeout=00:00:30] (Verbose, MqttChannelAdapter/7)
SRV>> 10:16:26.798 Error while accepting connection at default endpoint. (Error, MqttTcpServerAdapter/3)
System.InvalidOperationException: A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)
   at Windows.Networking.Sockets.StreamSocketControl.put_NoDelay(Boolean value)
   at MQTTnet.Implementations.MqttTcpServerAdapter.AcceptDefaultEndpointConnectionsAsync(StreamSocketListener sender, StreamSocketListenerConnectionReceivedEventArgs args)
```

and the source of the server :
```C#
    public sealed class StartupTask : IBackgroundTask
    {
        private BackgroundTaskDeferral deferral;
        private IMqttServer server;

        public void Run(IBackgroundTaskInstance taskInstance)
        {
            deferral = taskInstance.GetDeferral();
            taskInstance.Canceled += TaskInstanceOnCanceled;

            MqttNetGlobalLogger.LogMessagePublished += LogMessagePublished;

            var options = new MqttServerOptionsBuilder()
                          .WithConnectionBacklog(100)
                          .WithDefaultEndpointPort(Constants.MqttPort)
                          .WithDefaultCommunicationTimeout(TimeSpan.FromSeconds(30))
                          .WithConnectionValidator(ValidateConnection);

            server = new MqttFactory().CreateMqttServer();

            server.Started += ServerStarted;
            server.ClientConnected += ClientConnected;
            server.ClientDisconnected += ClientDisconnected;
            server.ClientSubscribedTopic += ClientSubscribedTopic;
            server.ClientUnsubscribedTopic += ClientUnsubscribedTopic;

            server.StartAsync(options.Build()).GetAwaiter().GetResult();
        }

        private void TaskInstanceOnCanceled(IBackgroundTaskInstance sender, BackgroundTaskCancellationReason reason)
        {
            if (deferral == null) return;

            if (server != null)
            {
                server.StopAsync().GetAwaiter().GetResult();

                server.Started -= ServerStarted;
                server.ClientConnected -= ClientConnected;
                server.ClientDisconnected -= ClientDisconnected;
                server.ClientSubscribedTopic -= ClientSubscribedTopic;
                server.ClientUnsubscribedTopic -= ClientUnsubscribedTopic;
            }

            MqttNetGlobalLogger.LogMessagePublished -= LogMessagePublished;

            deferral.Complete();
            deferral = null;
        }

        private void LogMessagePublished(object sender, MqttNetLogMessagePublishedEventArgs e)
        {
            var msg = new StringBuilder();
            msg.AppendFormat("{0:HH:mm:ss.fff} {4} ({1}, {3}/{2})", 
                             e.TraceMessage.Timestamp, e.TraceMessage.Level, e.TraceMessage.ThreadId,
                             e.TraceMessage.Source, e.TraceMessage.Message);
            if (e.TraceMessage.Exception != null)
            {
                msg.AppendLine();
                msg.Append(e.TraceMessage.Exception);
            }
            Debug.WriteLine($"SRV>> {msg}");
        }

        private void ValidateConnection(MqttConnectionValidatorContext c)
        {
            Debug.WriteLine($"SRV > Validate connection {c.ClientId}, user '{c.Username}', pwd '{c.Password}'");
            c.ReturnCode = MqttConnectReturnCode.ConnectionAccepted;
        }

        private void ClientUnsubscribedTopic(object sender, MqttClientUnsubscribedTopicEventArgs e)
        {
            Debug.WriteLine($"SRV > Client {e.ClientId} unsubscribed from {e.TopicFilter}");
        }

        private void ClientSubscribedTopic(object sender, MqttClientSubscribedTopicEventArgs e)
        {
            Debug.WriteLine($"SRV > Client {e.ClientId} subscribed to {e.TopicFilter}");
        }

        private void ClientDisconnected(object sender, MqttClientDisconnectedEventArgs e)
        {
            Debug.WriteLine($"SRV> Client {e.Client.ClientId} disconnected, clean: {e.WasCleanDisconnect}, pending msg {e.Client.PendingApplicationMessages}");
        }

        private void ClientConnected(object sender, MqttClientConnectedEventArgs e)
        {
            Debug.WriteLine($"SRV > Client {e.Client.ClientId} connected");
        }

        private void ServerStarted(object sender, MqttServerStartedEventArgs e)
        {
            Debug.WriteLine("SRV > Started");
        }
    }
```

I also join the the solution with client and server.
[MqttNetPiTest.zip](https://github.com/chkr1011/MQTTnet/files/1946188/MqttNetPiTest.zip)

Tell me if you want me to do some specific tests on the Pi.

Best regards,

Stéphane

**Comment by chkr1011** [comment]
Sorry the support for UWP was broken. Please try again with nuget _v.2.7.5-RC2_.

**Comment by SNival** [comment]
Hi Christian,

The problem still persists.
Having MqttNetGlobalLogger enabled on both client and server seems to prevent disconnections: it ran perfectly for 20 minutes. With single side or no logging, it disconnects within the minute.

I put the logs in the joinded excel sheet.
[Logs MQTT rc2.xlsx](https://github.com/chkr1011/MQTTnet/files/1950350/Logs.MQTT.rc2.xlsx)

Best regards

**Comment by SNival** [comment]
Sorry, the message of the exception is 'An existing connection was forcibly closed by remote host'.
If I try to match server and client logs, I think the server closes the connexion due to not receiving any packet / keep alive. In this case the client exception wouldn't be abnormal.
For your information, if I extend the keep alive period to a few minutes, I still get disconnections.

I downloaded the dev branch and had a look at global logging, but I can't find any clue why logging on both apps prevent the problem from occuring.
Inside my logging, I use a SysLog UDP writer and the MS diagnostic logging channel...

**Comment by SNival** [comment]
Hi,

I tried with release 2.7.5 but the problem is still present.
I left the app running with logging on client and server, and found the disconnections also occurs in that case, but far less frequently (2-3 times a day, opposed to a few tens of seconds without logging).

**Comment by chkr1011** [comment]
This is very strange. Especially because the log seems to _fix_ it. Is it possible that you test it with a disabled client log? If it still works I can focus on the server while finding a solution.

**Comment by SNival** [comment]
Sorry for the delay,

With logging enabled, disconnections aren't completely fixed, but they occur very rarely.
If i remove logging on the client, disconnections come back.
It's the fact that I call the actual logging that "prevent" the problem, if I just prepare the data to be logged without logging, it disconnects.
Maybe a timing problem ? I thought the MS diagnotic channel had some internal locking to prevent concurrent access, that may help but removing it and just keeping syslog changes nothing : lower disconnections when enabled...

Is there something I can do to help you ?

Best regards

**Comment by chkr1011** [comment]
Hi,
I released 2.8.0-alpha5 which fixes several connection problems. For me the UWP channel works for a long time without reconnects. Please let me know if the new version works for you.
Best regards
Christian

**Comment by SNival** [comment]
Hi,
The test solution using the new version doesn't disconnect.
As soon as the beta arrives, I will test it in our project.
Great job !

Best regards
