### ISSUE TITLE
Mqtt Server: System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by ahmadalli** [chkr1011/MQTTnet#227]
Hi
I'm getting this error after a while (a client connects, then disconnects and tries to connect again)
here's my trace (verbose and info both mapped to info)

```
2018-04-18 16:20:27.035 +04:30 [INF] [2018-04-18T16:20:27.0181148+04:30] [1] [MqttServer]: Started.
2018-04-18 16:21:05.392 +04:30 [INF] [2018-04-18T16:21:05.3904435+04:30] [9] [MqttServer]: Client '1000000': Connected.
2018-04-18 16:22:08.333 +04:30 [INF] [2018-04-18T16:22:08.3321950+04:30] [4] [MqttServer]: Client '1000000': Disconnected (clean=False).
2018-04-18 16:22:13.674 +04:30 [WRN] [2018-04-18T16:22:13.6722901+04:30] [9] [MqttClientSession]: Client '1000000': Did not receive any packet or keep alive signal.
2018-04-18 16:22:13.677 +04:30 [INF] [2018-04-18T16:22:13.6754948+04:30] [9] [MqttClientSession]: Client '1000000': Timeout while waiting for KeepAlive packet.
2018-04-18 16:22:13.728 +04:30 [INF] [2018-04-18T16:22:13.7269843+04:30] [9] [MqttClientSession]: Client '1000000': Session stopped.
2018-04-18 16:22:14.665 +04:30 [INF] [2018-04-18T16:22:14.6639509+04:30] [9] [MqttServer]: Client '1000000': Connected.
2018-04-18 16:22:36.671 +04:30 [INF] [2018-04-18T16:22:36.6691648+04:30] [3] [MqttServer]: Client '1000000': Disconnected (clean=False).
2018-04-18 16:22:42.967 +04:30 [INF] [2018-04-18T16:22:42.9655173+04:30] [4] [MqttServer]: Client '1000000': Connected.
2018-04-18 16:22:43.529 +04:30 [ERR] [2018-04-18T16:22:43.5260279+04:30] [16] [MqttClientPendingMessagesQueue]: Sending publish packet failed (ClientId: 1000000).
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MqttChannelAdapter'.
   at MQTTnet.Adapter.MqttChannelAdapter.ThrowIfDisposed() in Adapter\MqttChannelAdapter.cs:line 253
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketsAsync(TimeSpan timeout, CancellationToken cancellationToken, IEnumerable`1 packets) in Adapter\MqttChannelAdapter.cs:line 54
   at MQTTnet.Server.MqttClientPendingMessagesQueue.<SendNextQueuedPacketAsync>d__13.MoveNext() in Server\MqttClientPendingMessagesQueue.cs:line 96
2018-04-18 16:22:43.558 +04:30 [INF] [2018-04-18T16:22:43.5573650+04:30] [16] [MqttClientSession]: Client '1000000': Session stopped.
2018-04-18 16:22:53.750 +04:30 [INF] [2018-04-18T16:22:53.7485653+04:30] [3] [MqttServer]: Client '1000000': Disconnected (clean=False).
2018-04-18 16:22:58.492 +04:30 [WRN] [2018-04-18T16:22:58.4906067+04:30] [14] [MqttClientSession]: Client '1000000': Did not receive any packet or keep alive signal.
2018-04-18 16:22:58.494 +04:30 [INF] [2018-04-18T16:22:58.4926349+04:30] [14] [MqttClientSession]: Client '1000000': Timeout while waiting for KeepAlive packet.
2018-04-18 16:23:05.204 +04:30 [INF] [2018-04-18T16:23:05.2027056+04:30] [9] [MqttServer]: Client '1000000': Connected.
2018-04-18 16:23:05.312 +04:30 [ERR] [2018-04-18T16:23:05.3083129+04:30] [14] [MqttClientPendingMessagesQueue]: Sending publish packet failed (ClientId: 1000000).
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MqttChannelAdapter'.
   at MQTTnet.Adapter.MqttChannelAdapter.ThrowIfDisposed() in Adapter\MqttChannelAdapter.cs:line 253
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketsAsync(TimeSpan timeout, CancellationToken cancellationToken, IEnumerable`1 packets) in Adapter\MqttChannelAdapter.cs:line 54
   at MQTTnet.Server.MqttClientPendingMessagesQueue.<SendNextQueuedPacketAsync>d__13.MoveNext() in Server\MqttClientPendingMessagesQueue.cs:line 96
2018-04-18 16:23:05.350 +04:30 [INF] [2018-04-18T16:23:05.3482909+04:30] [14] [MqttClientSession]: Client '1000000': Session stopped.
2018-04-18 16:23:15.512 +04:30 [INF] [2018-04-18T16:23:15.5108862+04:30] [3] [MqttServer]: Client '1000000': Disconnected (clean=False).
2018-04-18 16:23:30.957 +04:30 [INF] [2018-04-18T16:23:30.9556463+04:30] [9] [MqttServer]: Client '1000000': Connected.
2018-04-18 16:23:31.729 +04:30 [ERR] [2018-04-18T16:23:31.7226459+04:30] [14] [MqttClientPendingMessagesQueue]: Sending publish packet failed (ClientId: 1000000).
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MqttChannelAdapter'.
   at MQTTnet.Adapter.MqttChannelAdapter.ThrowIfDisposed() in Adapter\MqttChannelAdapter.cs:line 253
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketsAsync(TimeSpan timeout, CancellationToken cancellationToken, IEnumerable`1 packets) in Adapter\MqttChannelAdapter.cs:line 54
   at MQTTnet.Server.MqttClientPendingMessagesQueue.<SendNextQueuedPacketAsync>d__13.MoveNext() in Server\MqttClientPendingMessagesQueue.cs:line 96
2018-04-18 16:23:31.757 +04:30 [INF] [2018-04-18T16:23:31.7561194+04:30] [14] [MqttClientSession]: Client '1000000': Session stopped.
2018-04-18 16:23:41.936 +04:30 [INF] [2018-04-18T16:23:41.9344995+04:30] [3] [MqttServer]: Client '1000000': Disconnected (clean=False).
```

**Comment by ahmadalli** [comment]
sorry for my late response. I think this issue has been resolved
