### ISSUE TITLE
Server closes client connection after error on processing data from client

### ISSUE THREAD

**Issue by konak** [chkr1011/MQTTnet#302]
Hi !

We have an issue with closing connection, when sending small packets to server. After turning the trace of the component we see that there is an exception inside server component:

MQTTnet.Exceptions.MqttCommunicationException: Index was outside the bounds of the array. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
    at MQTTnet.Serializer.MqttPacketReader.ReadUInt16()

Here is the full trace during packet send and disconnect process:

>> [2018-06-05T15:44:50.8770379+04:00] [27] [MqttClientPendingMessagesQueue] [Verbose]: Enqueued packet (ClientId: 43d55bba-ba0d-4289-8b0b-4cd46638fdf6_BE98304E-86D7-4E93-A41B-DD124F1C4176).
>> [2018-06-05T15:44:50.8770638+04:00] [28] [MqttChannelAdapter] [Verbose]: TX >>> Publish: [Topic=1562] [Payload.Length=223] [QoSLevel=AtMostOnce] [Dup=False] [Retain=False] [PacketIdentifier=] [Timeout=00:00:04]
>> [2018-06-05T15:44:50.8792872+04:00] [28] [MqttClientPendingMessagesQueue] [Verbose]: Enqueued packet sent (ClientId: 43d55bba-ba0d-4289-8b0b-4cd46638fdf6_BE98304E-86D7-4E93-A41B-DD124F1C4176).
>> [2018-06-05T15:44:50.8796490+04:00] [7] [MqttChannelAdapter] [Verbose]: TX >>> PubRec [Timeout=00:00:04]
>> [2018-06-05T15:44:50.9164323+04:00] [27] [MqttChannelAdapter] [Verbose]: RX <<< PubRel
>> [2018-06-05T15:44:50.9169804+04:00] [27] [MqttChannelAdapter] [Verbose]: TX >>> PubComp [Timeout=00:00:04]
>> [2018-06-05T15:44:54.4433034+04:00] [27] [MqttClientSession] [Warning]: Client '43d55bba-ba0d-4289-8b0b-4cd46638fdf6_BE98304E-86D7-4E93-A41B-DD124F1C4176': Communication exception while processing client packets.
MQTTnet.Exceptions.MqttCommunicationException: Index was outside the bounds of the array. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MQTTnet.Serializer.MqttPacketReader.ReadUInt16()
   at MQTTnet.Serializer.MqttPacketSerializer.DeserializePublish(MqttPacketReader reader, MqttPacketHeader mqttPacketHeader)
   at MQTTnet.Serializer.MqttPacketSerializer.Deserialize(MqttPacketHeader header, MemoryStream body)
   at MQTTnet.Adapter.MqttChannelAdapter.<>c__DisplayClass13_0.<<ReceivePacketAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Server.MqttClientSession.<ReceivePacketsAsync>d__36.MoveNext()
>> [2018-06-05T15:44:54.4782298+04:00] [27] [MqttClientSession] [Verbose]: Client 43d55bba-ba0d-4289-8b0b-4cd46638fdf6_BE98304E-86D7-4E93-A41B-DD124F1C4176: Stopped checking keep alive timeout.
>> [2018-06-05T15:44:54.4785829+04:00] [27] [MqttClientSession] [Info]: Client '43d55bba-ba0d-4289-8b0b-4cd46638fdf6_BE98304E-86D7-4E93-A41B-DD124F1C4176': Session stopped.
>> [2018-06-05T15:44:54.4786226+04:00] [27] [MqttChannelAdapter] [Verbose]: Disconnecting [Timeout=00:00:04]
>> [2018-06-05T15:44:54.4789953+04:00] [27] [MqttServer] [Info]: Client '43d55bba-ba0d-4289-8b0b-4cd46638fdf6_BE98304E-86D7-4E93-A41B-DD124F1C4176': Disconnected (clean=False).

Wish you all the best !

**Comment by GieltjE** [comment]
Could this be related to #161 ?

**Comment by konak** [comment]
No, the exception happens the same moment we sending data (without any timeout ...)

**Comment by chkr1011** [comment]
The issue here is that a socket close is not properly detected when reading the UInt16.

**Comment by chkr1011** [comment]
This is fixed in version 2.8.0.
