### ISSUE TITLE
Address family not supported exception under linux-arm

### ISSUE THREAD

**Issue by smuellener** [chkr1011/MQTTnet#307]
When using MQTTnet on a Raspberry Pi like hardware (armhf, dotnet publish for linux-arm) I get the following exception when creating the Socket:

```
Unhandled Exception: MQTTnet.Exceptions.MqttCommunicationException: Address family not supported by protocol ---> System.Net.Sockets.SocketException: Address family not supported by protocol
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at MQTTnet.Implementations.MqttTcpChannel.<ConnectAsync>d__11.MoveNext()
   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__0.MoveNext()
   at MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__23.MoveNext()
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__26.MoveNext()
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__26.MoveNext()
```

Creating the Socket using the following works and does not throw an exception:

`new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp)`

My suggestion is, trying it your way but catching the AddressFamily not supported SocketException and then trying again with AddressFamily.InterNetwork. Only if that fails, throw the exception. Would you agree with such a solution? Should I prepare a pull request?

**Comment by chkr1011** [comment]
Hi, thank you for reporting this issue and providing a solution.
I will add this. I will also check if there are more changes required to still support IPv6 because _InterNetwork_ is limited to IPv4 only.
Best regards
Christian

**Comment by smuellener** [comment]
Yes, the client might work on ubuntu1806 but excepts under linux-arm. In MQTTnet.Implementations.MqttTcpChannel. The stack trace you can see above. You have not changed this yet, correct?

**Comment by smuellener** [comment]
netcoreapp2.1 resolved the issue for linux-arm. tested with 2.8.0-alpha.5
