### ISSUE TITLE
Can't connect with client certificate authentication

### ISSUE THREAD

**Issue by timkoers** [chkr1011/MQTTnet#312]
I am trying to connect with client certificate authentication to our MQTT server.

```
X509Certificate2 cert = new X509Certificate2(AppContext.BaseDirectory + @"filename.pfx", "password");

				singleton.clientOptions = new ManagedMqttClientOptionsBuilder()
				.WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
				.WithClientOptions(new MqttClientOptionsBuilder()
					.WithClientId(cert.Subject.Replace("CN=", ""))
					.WithTcpServer("hostname", 8884)
					.WithTls(true, true, false,
			                cert.Export(X509ContentType.Pfx)).Build())
				.Build();
```

The pfx file consists of a pem crt and a pem private key.
The pfx file was created with the following command:
openssl pkcs12 -inkey pki/private/WD.05.021-dashboard.key -in pki/issued/WD.05.021-dashboard.crt -export -out pki/issued/WD.05.021-dashboard.pfx

Then when it tries to connect, it gives back a No matching object found.

21:21:34.380 [5 MqttClient Error] Error while connecting with server.
```
MQTTnet.Exceptions.MqttCommunicationException: Geen overeenkomend object gevonden. (No matching object found)

Initialize ---> System.Runtime.InteropServices.COMException: Geen overeenkomend object gevonden. (No matching object found)

Initialize
   at Windows.Security.Cryptography.Certificates.Certificate..ctor(IBuffer certBlob)
   at MQTTnet.Implementations.MqttTcpChannel.LoadCertificate(MqttClientTcpOptions options)
   at MQTTnet.Implementations.MqttTcpChannel.<ConnectAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Internal.TaskExtensions.<TimeoutAfter>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ExecuteAndWrapExceptionAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__26.MoveNext()
21:21:34.387 [5 MqttChannelAdapter Verbose] Disconnecting [Timeout=00:00:10]
21:21:34.388 [5 MqttClient Verbose] Disconnected from adapter.
```

Is there a client certificate authentication with private key implementation available for the UWP version running on Windows 10 IoT Core?

I badly need one and since M2MQTT just didn't provide any certificate options at all when compiling for ARM, this is my only hope.

**Comment by SeppPenner** [comment]
@timkoers I don't think this is available yet.

**Comment by chkr1011** [comment]
I will close this due to inactivity. If this is still relevant please reopen the ticket. You can also try to use the .net standard version of the nuget package. It may work better if you already using an IoT Core version with .netstandard2.0 support.
