### ISSUE TITLE
Unobserved MqttCommunicationClosedGracefullyException

### ISSUE THREAD

**Issue by GieltjE** [chkr1011/MQTTnet#322]
Couldn't find any reference to this code using the search, so I guess it's in the dev branch.
Shouldn't this throw the disconnected event?

```There are no context policies.

 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' was thrown.

   at MQTTnet.Serializer.MqttPacketReader.<ReadFixedHeaderAsync>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__22.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__21.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Client.MqttClient.<ReceivePacketsAsync>d__40.MoveNext()

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

---> (Inner Exception #0) MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' was thrown.

   at MQTTnet.Serializer.MqttPacketReader.<ReadFixedHeaderAsync>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__22.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__21.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MQTTnet.Client.MqttClient.<ReceivePacketsAsync>d__40.MoveNext()<---```

**Comment by chkr1011** [comment]
Hi,
please test with the latest 2.8.0 version. Probably this is a an already fixed issue.
Best regards
Christian

**Comment by poumason** [comment]
I already use the 2.8.2, the issue still be happened. 
I don't know why read bytes is  0 must be throw exception? maybe use ignore this condition?
