### ISSUE TITLE
ManagedClient Connection Problem

### ISSUE THREAD

**Issue by setamodius** [chkr1011/MQTTnet#328]
Hi. 
I am using ManagedClient v2.8.0-rc3. I have a problem. I can't connect my server with this code.
```csharp
IManagedMqttClientOptions options = new ManagedMqttClientOptionsBuilder()
            .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
            .WithClientOptions(new MqttClientOptionsBuilder()
                .WithProtocolVersion(MQTTnet.Serializer.MqttProtocolVersion.V311)
                .WithClientId("1234567890123456")
                .WithTcpServer("10.3.4.241", 1883)
                .WithCredentials("master", "furhgv")
                .WithCleanSession()
                .WithWillMessage(new MqttApplicationMessageBuilder()
                    .WithTopic("MQTT/12345678-master/Status")
                    .WithPayload("timestamp:23.06.2018 19:36:56,status:disconnected")
                    .WithExactlyOnceQoS()
                    .WithRetainFlag()
                    .Build())
                .Build())
            .Build();
            mqttClient = new MqttFactory().CreateManagedMqttClient();
```
but when I change 'clientid' from '1234567890123456' to '123456789012345' or reduce number of characters in 'willmessage',  I can connect to server.

**Comment by chkr1011** [comment]
Could you please also add trace messages? Or is there probably nothing interesting shown?

**Comment by setamodius** [comment]
I added trace messages.
```
>> [2018-06-24T07:08:12.8978534Z] [3] [MqttClient] [Verbose]: Trying to connect with server (10.3.4.241:1883).
>> [2018-06-24T07:08:12.9018424Z] [3] [MqttClient.MqttChannelAdapter] [Verbose]: Connecting [Timeout=00:00:10]
>> [2018-06-24T07:08:12.9287706Z] [4] [MqttClient] [Verbose]: Connection with server established.
>> [2018-06-24T07:08:12.9407386Z] [3] [MqttClient] [Verbose]: Start receiving packets.
>> [2018-06-24T07:08:12.9497183Z] [4] [MqttClient.MqttChannelAdapter] [Verbose]: TX >>> Connect: [ClientId=1234567890123456] [Username=master] [Password=master] [KeepAlivePeriod=15] [CleanSession=True]
>> [2018-06-24T07:08:12.9606856Z] [4] [MqttClient] [Error]: Error while connecting with server.
MQTTnet.Exceptions.MqttCommunicationException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds. ---> System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at MQTTnet.Serializer.MqttPacketWriter.Write(Byte[] array, Int32 offset, Int32 count)
   at MQTTnet.Serializer.MqttPacketWriter.WriteWithLengthPrefix(Byte[] value)
   at MQTTnet.Serializer.MqttPacketWriter.WriteWithLengthPrefix(String value)
   at MQTTnet.Serializer.MqttPacketSerializer.Serialize(MqttConnectPacket packet, MqttPacketWriter packetWriter)
   at MQTTnet.Serializer.MqttPacketSerializer.SerializePacket(MqttBasePacket packet, MqttPacketWriter packetWriter)
   at MQTTnet.Serializer.MqttPacketSerializer.Serialize(MqttBasePacket packet)
   at MQTTnet.Adapter.MqttChannelAdapter.<SendPacketAsync>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.<SendPacketAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<AuthenticateAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__26.MoveNext()

```

**Comment by chkr1011** [comment]
I released a fixed version (RC4). Please let me know if this version works for you.

**Comment by setamodius** [comment]
It is working. Thanks.

**Comment by chkr1011** [comment]
Cool 👍 Thank you for reporting this issue.
