### ISSUE TITLE
AggregateException, MqttCommunicationException after several connection failures

### ISSUE THREAD

**Issue by GieltjE** [chkr1011/MQTTnet#423]
Environment: DotNet 4.7.2, Win10 (both X86 and X64)

We are using the Disconnected event to attempt to reconnect (in this case we are attempting to connect to an endpoint which is not listening (e.g. the server is down)):

```
            Task connection = null;
            try
            {
                connection = MqttClient.ConnectAsync(_tcpOptions);
                connection.Wait();
            }
            catch (Exception exception)
            {
                MessageBox.Show("A" + connection.Exception.ToString());
            }

            if (connection.IsFaulted)
            {
                MessageBox.Show("B" + connection.Exception.ToString());
            }
```
We actively handle the exception as "required" by tasks, yet still we are greeted with the following unobserved task exceptions from within MQTTnet:

```
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> MQTTnet.Exceptions.MqttCommunicationException: No connection could be made because the target machine actively refused it [::ffff:192.168.198.8]:1883 ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it [::ffff:192.168.198.8]:1883

   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)

   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__317_0(IAsyncResult iar)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Implementations.MqttTcpChannel.<ConnectAsync>d__12.MoveNext() in \MQTTnet\Implementations\MqttTcpChannel.cs:line 59

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Internal.TaskExtensions.<TimeoutAfterAsync>d__0.MoveNext() in \MQTTnet\Internal\TaskExtensions.cs:line 19

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__20.MoveNext() in \MQTTnet\Adapter\MqttChannelAdapter.cs:line 57

   --- End of inner exception stack trace ---

   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception) in \MQTTnet\Adapter\MqttChannelAdapter.cs:line 254

   at MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__20.MoveNext() in \MQTTnet\Adapter\MqttChannelAdapter.cs:line 68

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Client.MqttClient.<ConnectAsync>d__27.MoveNext() in \MQTTnet\Client\MqttClient.cs:line 66

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at MQTTnet.Client.MqttClient.<ConnectAsync>d__27.MoveNext() in \MQTTnet\Client\MqttClient.cs:line 94

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

---> (Inner Exception #0) MQTTnet.Exceptions.MqttCommunicationException: No connection could be made because the target machine actively refused it [::ffff:192.168.198.8]:1883 ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it [::ffff:192.168.198.8]:1883

   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)

   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__317_0(IAsyncResult iar)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Implementations.MqttTcpChannel.<ConnectAsync>d__12.MoveNext() in \MQTTnet\Implementations\MqttTcpChannel.cs:line 59

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Internal.TaskExtensions.<TimeoutAfterAsync>d__0.MoveNext() in \MQTTnet\Internal\TaskExtensions.cs:line 19

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__20.MoveNext() in \MQTTnet\Adapter\MqttChannelAdapter.cs:line 57

   --- End of inner exception stack trace ---

   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception) in \MQTTnet\Adapter\MqttChannelAdapter.cs:line 254

   at MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__20.MoveNext() in \MQTTnet\Adapter\MqttChannelAdapter.cs:line 68

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

   at MQTTnet.Client.MqttClient.<ConnectAsync>d__27.MoveNext() in \MQTTnet\Client\MqttClient.cs:line 66

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at MQTTnet.Client.MqttClient.<ConnectAsync>d__27.MoveNext() in \MQTTnet\Client\MqttClient.cs:line 94<---
```

-- Edit, run the tests against the development source to include line numbers.

For some reason this happens within the first 3 attempts on our big project, however when the same code (basically 50 lines of code) is copied to an empty project all is fine.

**Comment by chkr1011** [comment]
Hi, I released 2.8.4-rc2. Please let me know if this version works for you.

**Comment by GieltjE** [comment]
Seems to work properly, will be running some more extensive tests tonight.

What was the problem?

**Comment by GieltjE** [comment]
Confirmed fixed 💯
