### ISSUE TITLE
Error: The remote party closed the WebSocket connection without completing the close handshake.

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#437]
I updated to the last stable version. Before WebSocket works. After update I 've this error:

[```
MqttHostedServer.MqttServer.MqttClientSessionsManager] [Error]: The remote party closed the WebSocket connection without completing the close handshake.
MQTTnet.Exceptions.MqttCommunicationException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.MissingMethodException: Method not found: 'Boolean System.Memory`1.TryGetArray(System.ArraySegment`1<!0> ByRef)'.
   at System.Net.WebSockets.ManagedWebSocketExtensions.ReadAsync(Stream stream, Memory`1 destination, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__71.MoveNext()
```

Why?

**Comment by dealproc** [comment]
@biapar Did you come to a conclusion on how to resolve this?

**Comment by stefxx** [comment]
I know this is old, however this issue still exists in 3.1.2. Did anyone find a workaround to keep the WebSocket session alive?

I can set the timeout to infinite by this statement:

`ServicePointManager.MaxServicePointIdleTime = Timeout.Infinite`

but that means that the issue occurs every 15 minutes (instead of every 100 seconds) which is an improvement but still not ideal.

Thanks!
