### ISSUE TITLE
MqttCommunicationClosedGracefullyException every 30s

### ISSUE THREAD

**Issue by cocowalla** [chkr1011/MQTTnet#477]
I'm using MQTTnet with EMQX (docker image `emqx/emqx:v3.0-rc.3`), and it works well with standard, TCP-based MQTT.

However, with MQTT over WebSockets, the connection gets disconnedted exactly every 30 seconds:

```
Exception of type 'MQTTnet.Exceptions.MqttCommunicationClosedGracefullyException' was thrown.
   at MQTTnet.Serializer.MqttPacketReader.ReadFixedHeaderAsync(IMqttChannel channel, Byte[] fixedHeaderBuffer, Byte[] singleByteBuffer, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceiveAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ReceivePacketsAsync(CancellationToken cancellationToken)
```

```
var clientCert = new X509Certificate2("my-cert.p12", String.Empty, X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet);

var tlsParams = new MqttClientOptionsBuilderTlsParameters
{
	UseTls = true,
	AllowUntrustedCertificates = true,
	IgnoreCertificateChainErrors = true,
	IgnoreCertificateRevocationErrors = true,
	Certificates = new [] { clientCert.Export(X509ContentType.SerializedCert) },
	CertificateValidationCallback = (serverCert, chain, policyErrors, clientOptions) => true
};

var options = new ManagedMqttClientOptionsBuilder()
	.WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
	.WithClientOptions(new MqttClientOptionsBuilder()
		.WithCommunicationTimeout(TimeSpan.FromSeconds(60))
		.WithWebSocketServer("wss://127.0.0.1:8084/mqtt")
		.WithClientId("test-client")
		.WithCleanSession()
		.WithTls(tlsParams).Build())
	.Build();

var mqttClient = new MqttFactory().CreateManagedMqttClient();
await mqttClient.StartAsync(options);
```

**Comment by dealproc** [comment]
I am in the midst of moving cheese in our data centers.  once completed, i'll enhance logging into the stack that's using mqtt and i'll see if this is indeed what i am seeing.

**Comment by dealproc** [comment]
@cocowalla Are you using k8s or something with an nginx ingress / application gateway?  I'm wondering if it may have something to do with the inginx settings, and not an mqtt setting.

**Comment by cocowalla** [comment]
I'm just using Docker Compose on a laptop, running a single EMQ X container, with nothing in front of it.

I'm not certain, but I also seem to recall earlier having the same problem using MqttNet with a RabbitMQ broker running MQTT plugins.

**Comment by SeppPenner** [comment]
Is this still relevant?
