### ISSUE TITLE
ManagedMqttNet unable to get stable connections 

### ISSUE THREAD

**Issue by viplovedeshmukh** [chkr1011/MQTTnet#493]
I'm trying to connect 500 clients using ManagedMqttNet library with default setting but not able to get stable connections, after 280+ connection the library throws the exception with message "A task was cancelled". The other connected clients automatically got disconnected within some time.

Exception:

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<StartReceivingPacketsAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Subscriber.SubscriberApplicationContext.<ConnectAsync>d__23.MoveNext()

**Comment by viplovedeshmukh** [comment]
Hi Christian,

Please find below details:

1. Are you using TCP or WebSockets?
>>> I am using the MQTT TCP Port

2. Are you testing with 500 clients from the same machine/process?
>>> yes, from single machine and single process, trying to make 500 connections using ManagedMQTTNetClient

3. Which version of the library are you using?
>>> 2.8.4

4. Are you using MQTTnet server or another one like mosquitto?
>>> MQTT Broker is Solace

Thanks,
Viplove

**Comment by SeppPenner** [comment]
@viplovedeshmukh Can you please re-try this with the latest version and maybe also provide a code snippet? Thank you.

**Comment by SeppPenner** [comment]
I will close this issue now due to inactivity, feel free to re-open this issue if you have further questions or this issue still applies to th latest version.

**Comment by ValeryYegorov** [comment]
Hi Christian,

I have same issue with latest MQTTnet version

**Comment by chkr1011** [comment]
Please try with the latest version and reopen this ticket if the problem still occurs.
