### ISSUE TITLE
FileLoadException after ConnectAsync

### ISSUE THREAD

**Issue by schlotter** [chkr1011/MQTTnet#538]
In my sample application I connect to the server like this:

```
this.clientOptions = new MQTTnet.Client.MqttClientOptionsBuilder()
    .WithTcpServer("localhost", 8000)
    .Build();
this.client = new MqttFactory().CreateMqttClient();

this.client.Disconnected += this.OnClientDisconnected;
await this.client.ConnectAsync(this.clientOptions);
```

Note: On my system, at "localhost", port 8000, no MQTT server is running.

### Observed behavior

`ConnectAsync` fails and `OnClientDisconnected` is immediately called. The following exception is given and my application crashes.

### From debugging in Visual Studio
Message: Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:    at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<ConnectAsync>d__30.MoveNext()

### From Windows Event Viewer
Application: MyApplication.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at MQTTnet.Implementations.MqttTcpChannel+<ConnectAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[MQTTnet.Implementations.MqttTcpChannel+<ConnectAsync>d__12, MQTTnet, Version=2.8.5.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7]](<ConnectAsync>d__12 ByRef)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(System.Threading.CancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.<ConnectAsync>b__20_0(System.Threading.CancellationToken)
   at MQTTnet.Internal.TaskExtensions+<TimeoutAfterAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at MQTTnet.Adapter.MqttChannelAdapter+<ConnectAsync>d__20.MoveNext()

Exception Info: MQTTnet.Exceptions.MqttCommunicationException
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(System.Exception)
   at MQTTnet.Adapter.MqttChannelAdapter+<ConnectAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at MQTTnet.Client.MqttClient+<ConnectAsync>d__30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MQTTnet.Client.MqttClient+<ConnectAsync>d__30.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at Zeiss.Micro.EM.Hal.Comms.Mqtt.MqttClient+<SetupAndStartMqttClient>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

### Expected behavior
No FileLoadException and no application crash.

### Versions
Windows 10
MQTTnet v2.8.5
.NET Framework 4.6.1, x86

**Comment by schlotter** [comment]
I have now tried MQTTnet v3.0.0-alpha2 and get the same behavior and exception as above.

**Comment by chkr1011** [comment]
Hi,
are you maybe building a dedicated x86 build or x64? 
The binaries are set to "AnyCPU". 

I am also wondering why it fails in MqttTcpChannel. There are only .net libs used.
Could you please try to test it with the source code directly? And also with an attached debugger?

FileLoadException might indicate that the platform is wrong (x86 etc.). If a file is missing I would expect a FileNotFoundException. 

Could you also try to set a different target framework like 4.5 or .net Core (only for testing)?

Best regards
Christian

**Comment by schlotter** [comment]
Sorry for the late reply. I have not yet tried everything that you suggested.

I'm building as Any CPU, but launching as a 32-Bit process.

Here's what I found out so far:
1. Running the application as 64-Bit process does not make a difference. Still the same exception.
2. The file version of my System.Net.Sockets is 4.6.26011.1.

Next I will test with the source code directly, and also try a different target framework.

Also, please find extended exception information from Visual Studio Debug output:
```
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationException' in mscorlib.dll
The thread 0x6238 has exited with code 0 (0x0).
An exception of type 'MQTTnet.Exceptions.MqttCommunicationException' occurred in mscorlib.dll but was not handled in user code
Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

The thread 0x5d24 has exited with code 0 (0x0).
The thread 0x5db8 has exited with code 0 (0x0).
The thread 0x6044 has exited with code 0 (0x0).
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationException' in mscorlib.dll
The thread 0x6278 has exited with code 0 (0x0).
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>MyProgram.exe</AppDomain><Exception><ExceptionType>MQTTnet.Exceptions.MqttCommunicationException, MQTTnet, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7</ExceptionType><Message>Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)</Message><StackTrace>   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.&amp;lt;ConnectAsync&amp;gt;d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.&amp;lt;ConnectAsync&amp;gt;d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MQTTnet.Client.MqttClient.&amp;lt;ConnectAsync&amp;gt;d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyProgram.MqttClient.&amp;lt;SetupAndStartMqttClient&amp;gt;d__12.MoveNext() in MyCode\MqttClient.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()</StackTrace><ExceptionString>MQTTnet.Exceptions.MqttCommunicationException: Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---&amp;gt; System.IO.FileLoadException: Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at MQTTnet.Implementations.MqttTcpChannel.&amp;lt;ConnectAsync&amp;gt;d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp;amp; stateMachine)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.&amp;lt;ConnectAsync&amp;gt;b__20_0(CancellationToken t)
   at MQTTnet.Internal.MqttTaskTimeout.&amp;lt;WaitAsync&amp;gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.&amp;lt;ConnectAsync&amp;gt;d__20.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.&amp;lt;ConnectAsync&amp;gt;d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.&amp;lt;ConnectAsync&amp;gt;d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MQTTnet.Client.MqttClient.&amp;lt;ConnectAsync&amp;gt;d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyProgram.MqttClient.&amp;lt;SetupAndStartMqttClient&amp;gt;d__12.MoveNext() in MyCode\MqttClient.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()</ExceptionString><InnerException><ExceptionType>System.IO.FileLoadException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)</Message><StackTrace>   at MQTTnet.Implementations.MqttTcpChannel.&amp;lt;ConnectAsync&amp;gt;d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp;amp; stateMachine)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.&amp;lt;ConnectAsync&amp;gt;b__20_0(CancellationToken t)
   at MQTTnet.Internal.MqttTaskTimeout.&amp;lt;WaitAsync&amp;gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.&amp;lt;ConnectAsync&amp;gt;d__20.MoveNext()</StackTrace><ExceptionString>System.IO.FileLoadException: Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MQTTnet.Implementations.MqttTcpChannel.&amp;lt;ConnectAsync&amp;gt;d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp;amp; stateMachine)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.&amp;lt;ConnectAsync&amp;gt;b__20_0(CancellationToken t)
   at MQTTnet.Internal.MqttTaskTimeout.&amp;lt;WaitAsync&amp;gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.&amp;lt;ConnectAsync&amp;gt;d__20.MoveNext()

=== Pre-bind state information ===
LOG: DisplayName = System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/MyPath
LOG: Initial PrivatePath = NULL
Calling assembly : netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: MyProgram.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/MyPath/System.Net.Sockets.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
</ExceptionString></InnerException></Exception></TraceRecord>
An unhandled exception of type 'MQTTnet.Exceptions.MqttCommunicationException' occurred in mscorlib.dll
Could not load file or assembly 'System.Net.Sockets, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

The thread 0x5f2c has exited with code 0 (0x0).
The program '[2796] MyProgram.exe' has exited with code 0 (0x0).

```

**Comment by schlotter** [comment]
I have solved my issue temporarily by retargeting my application from .NET Framework 4.6.1 to 4.7.2. I have also downgraded back to the release version MQTTnet 2.8.5.

This is interesting because creating a new console application with .NET Framework 4.6.1 and using MQTTnet 2.8.5 to connect to a server works.

This is similar to issues #378 and #518.

**Comment by schlotter** [comment]
I have now retargeted back to .NET Framework 4.6.1 and MQTTnet 2.8.5 is working!
