### ISSUE TITLE
Clients with Last Will prevents the MqttServer from clean shutdown and restart

### ISSUE THREAD

**Issue by msallin** [chkr1011/MQTTnet#541]
As soon as there is a client with a last will connected to the MQTT-Server, it's not possible anymore to graceful stop the broker. 

There are three symptoms:
1) An unhandled exception 
2) The TCP-Socket is not closed and therefore it is not possible to start the Broker again
3) The last will is not executed (not sure if this is true, needs investigation)

The following exception is thrown:
```
System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Server.MqttClientSessionsManager.EnqueueApplicationMessage(MqttClientSession senderClientSession, MqttPublishPacket publishPacket)
   at MQTTnet.Server.MqttClientSession.Stop(MqttClientDisconnectType type, Boolean isInsideSession)
   at MQTTnet.Server.MqttClientSessionsManager.Stop()
   at MQTTnet.Server.MqttServer.<StopAsync>d__39.MoveNext()
```
If the MqttServer should be stopped and there is a client with a last will connected, the MqttServer tries to Enqueue the message with the last will.
Under the hood, this results in a call to `BlockingCollection.TryAddWithNoTimeValidation`.
This method takes a cancellation token and will throw an exception if cancellation is requested.
As the cancellation is requested during the stop, before calling `BlockingCollection.TryAddWithNoTimeValidation`, an exception is thrown.
This exception isn't handled and the rest of the code in the `MqttClientSessionsManager.Stop()` isn't executed.

EDIT:
I can submit a Pull Request but I'm not sure how this should be sovled.

**Comment by matthid** [comment]
Maybe this is related/identical to https://github.com/chkr1011/MQTTnet/pull/526?

**Comment by msallin** [comment]
Thank you for the hint. It is. Therefore I close this issue.
