### ISSUE TITLE
expected at least 1049 bytes but there a re only 54 bytes

### ISSUE THREAD

**Issue by maikebing** [chkr1011/MQTTnet#549]
fail: MQTTnet.Diagnostics.IMqttNetLogger[0]
      ID:,ThreadId:5,Source:MqttHostedServer.MqttServer.MqttClientSessionsManage
r,Timestamp:2019-02-13 10:02:42,Message:expected at least 1049 bytes but there a
re only 54 bytes
      Parameter name: _buffer
MQTTnet.Exceptions.MqttCommunicationException: expected at least 1049 bytes but
there are only 54 bytes
Parameter name: _buffer ---> System.ArgumentOutOfRangeException: expected at lea
st 1049 bytes but there are only 54 bytes
Parameter name: _buffer
   at MQTTnet.Serializer.MqttPacketBodyReader.ValidateReceiveBuffer(UInt16 lengt
h)
   at MQTTnet.Serializer.MqttPacketBodyReader.ReadWithLengthPrefix()
   at MQTTnet.Serializer.MqttPacketBodyReader.ReadStringWithLengthPrefix()
   at MQTTnet.Serializer.MqttPacketSerializer.DeserializeConnect(MqttPacketBodyR
eader body)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(TimeSpan timeout, Ca
ncellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ReceivePacketAsync(TimeSpan timeout, Ca
ncellationToken cancellationToken)
   at MQTTnet.Server.MqttClientSessionsManager.RunSessionAsync(IMqttChannelAdapt

**Comment by chkr1011** [comment]
Hi,
please provide some more information like sample code or trace output.
The plain exception it not really helpful.

Best regards
Christian

**Comment by JanEggers** [comment]
for me it looks like a malformed mqtt packet where some string fields length is bigger than the actual message

**Comment by maikebing** [comment]
In fact, I haven't found any valuable data at the moment, which only happens in a particular network environment, and it's not going to recur at the moment.

**Comment by chkr1011** [comment]
If you find more data or if this problem also appears with latest dev and/or preview nugets of 3.0.0 please let me know.
