### ISSUE TITLE
Stream ReadAsync stuck bug

### ISSUE THREAD

**Issue by biovoid** [chkr1011/MQTTnet#584]
Hi,
I got the bug when after timeout the client connection was not closed, it hangs for long time inside ReadAsync. Even when cancellation token was raised. I see your notice in the MqttTcpChannel.Dispose() method about stream disposing, but it should be like:
```
_stream?.Dispose();
_stream = null;

_socket?.Dispose();
_socket = null;
```
Disposing only _stream does not cancel ReadAsync in my case, so _socket should be also disposed.

**Comment by chkr1011** [comment]
Hi,
thank you for reporting this issue.
Is it possible to add a unit test for that? This would make it easier to test.
Best regards
Christian

**Comment by biovoid** [comment]
Hi,
I think its hard to make a unit test because it depends on GC behavior. In your code you just set _soket = null, and in this case the dispose method will be called only when GC collect him. I use master and develop branches and in both I had freezing after sometime. My devices are frequently connects/disconnects, also timeouts occurs. Previously I was trying fix this with GC.Collect(), but it helps partially, may be _socket is linked by someone.

**Comment by biovoid** [comment]
Also still have periodically freezing in some other place. After socket errors or timeouts, client can connect several times in sequence, but can't subscribe/publish.

**Comment by chkr1011** [comment]
I maybe found a reason. I added a UnitTest but it worked as expected. The socket was disposed perfectly. The stream will dispose the socket internally on its own dispose. The hierarchy is `NetworkStream > Socket`.  But when I checked the chain for SSL connections it was broken. The hierarchy is `SslStream > Networkstream > Socket`. So the disposal of the SSL stream should close the networks stream and the network stream should dispose the socket. But this was broken because of wrong parameters for stream constructors. That`s why you needed to dispose the socket. Are you using SSL connections? Or is this maybe another issue?

The fix is already pushed to develop branch.

**Comment by JanEggers** [comment]
https://github.com/dotnet/corefx/pull/36516/

FYI

**Comment by biovoid** [comment]
It seems that partially solved. In current version without a lot of my own disposes all over the code I have this bug. After some time of reconnecting/timeouts the remote device stop receiving messages, but subscribing was ok. I see that inside server there is a least two active client connections, and the all subscription messages are sending to old connection instance, but new connection instance do not receive any message. Also new connection instance can publish messages. After some time and disconnected all devices I see that several client instances are stopped in log. After this the device can connect and starts receive messages.

**Comment by biovoid** [comment]
I think the bug sequence for the same client_id (same device, low server hardware): connect > disconnect (immediately, start deleting this instance) > connect (immediately, before first instance is deleted) > subscribing (server attach subscribes to the first instance) ...
In this case all message will go to the first instance - will be skipped or smthing. And as the result I have connected device that can't receive messages, but is connected and subscribed.

**Comment by chkr1011** [comment]
What do you mean with "a lot of my own disposes all over the code ". Where did you add them?

**Comment by chkr1011** [comment]
Are you able to see the described behavior in the logs? I would like to reproduce it but I am not able to do so.

**Comment by biovoid** [comment]
Sorry, that was my mistake. I was testing prev version before your fix. Now I am testing right version and it seems stable. But when timeout occurs I am catching 
```
Communication exception while receiving client packets.MQTTnet.Exceptions.MqttCommunicationException: Cannot access a disposed object.
Object name: 'SslStream'. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.MqttTcpChannel.<ReadAsync>d__14.MoveNext() in \MQTTnet\Source\MQTTnet\Implementations\MqttTcpChannel.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Formatter.MqttPacketReader.<ReadFixedHeaderAsync>d__3.MoveNext() in \MQTTnet\Source\MQTTnet\Formatter\MqttPacketReader.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__35.MoveNext() in \MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 211
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in \MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 158
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception) in \MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 315
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in \MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MQTTnet.Server.MqttClientConnection.<RunInternalAsync>d__30.MoveNext() in \MQTTnet\Source\MQTTnet\Server\MqttClientConnection.cs:line 164
```

**Comment by chkr1011** [comment]
Thanks for the stack trace. So this looks like an exception from the server. But the line numbers are pointing to no useful line on code. At least when comparing with latest develop branch.

Do you really use the latest version? If not please try again with the current develop branch.

**Comment by biovoid** [comment]
Hi, 
I've tested again with newer version of the develop branch. The problem is more than exception. And I don't know if its server problem or windows/amazon/firewall. After this exception ocurrs several times in sequence the server can't accept new ssl connections at all. I tried to connect from different sources, and no one connects after this exception occurs. But the already connected clients are working. Here a log, after this no more connections.

```...

2019-04-19 20:34:47.2321  WARN MqttClientKeepAliveMonitor Client '74aa5490-12c3-4810-85fb-eec5bbd50b85': Did not receive any packet or keep alive signal.
2019-04-19 20:34:47.2321  WARN MqttClientConnection Client '74aa5490-12c3-4810-85fb-eec5bbd50b85': Communication exception while receiving client packets.MQTTnet.Exceptions.MqttCommunicationException: Cannot access a disposed object.
Object name: 'SslStream'. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.MqttTcpChannel.<ReadAsync>d__14.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Implementations\MqttTcpChannel.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Formatter.MqttPacketReader.<ReadFixedHeaderAsync>d__3.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Formatter\MqttPacketReader.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__35.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 211
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 158
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception) in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 315
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MQTTnet.Server.MqttClientConnection.<RunInternalAsync>d__29.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Server\MqttClientConnection.cs:line 155
2019-04-19 20:34:47.2321  INFO MqttClientConnection Client '74aa5490-12c3-4810-85fb-eec5bbd50b85': Session stopped.

...

2019-04-19 20:34:52.1901  INFO MqttClientConnection Client '74aa5490-12c3-4810-85fb-eec5bbd50b85': Session started.

...

2019-04-19 20:35:14.7071  WARN MqttClientKeepAliveMonitor Client '74aa5490-12c3-4810-85fb-eec5bbd50b85': Did not receive any packet or keep alive signal.
2019-04-19 20:35:14.7071  WARN MqttClientConnection Client '74aa5490-12c3-4810-85fb-eec5bbd50b85': Communication exception while receiving client packets.MQTTnet.Exceptions.MqttCommunicationException: Cannot access a disposed object.
Object name: 'SslStream'. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.MqttTcpChannel.<ReadAsync>d__14.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Implementations\MqttTcpChannel.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Formatter.MqttPacketReader.<ReadFixedHeaderAsync>d__3.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Formatter\MqttPacketReader.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__35.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 211
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 158
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception) in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 315
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MQTTnet.Server.MqttClientConnection.<RunInternalAsync>d__29.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Server\MqttClientConnection.cs:line 155
2019-04-19 20:35:14.7071  INFO MqttClientConnection Client '74aa5490-12c3-4810-85fb-eec5bbd50b85': Session stopped.

...

**Comment by biovoid** [comment]
Sometimes this exception occurs after connection accepted. Or may be client was disconnected at the same time.
```
2019-04-20 09:01:06.1057  INFO 74aa5490-12c3-4810-85fb-eec5bbd50b85 Connection accepted (f751fa8f86da4ef6b42d4b96e22fe874)
2019-04-20 09:01:06.1057  WARN MqttClientConnection Client '74aa5490-12c3-4810-85fb-eec5bbd50b85': Communication exception while receiving client packets.MQTTnet.Exceptions.MqttCommunicationException: Cannot access a disposed object.
Object name: 'SslStream'. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.MqttTcpChannel.<ReadAsync>d__14.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Implementations\MqttTcpChannel.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Formatter.MqttPacketReader.<ReadFixedHeaderAsync>d__3.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Formatter\MqttPacketReader.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__35.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 211
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 158
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception) in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 315
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MQTTnet.Server.MqttClientConnection.<RunInternalAsync>d__29.MoveNext() in C:\Repositories\project\dev\MQTTnet\Source\MQTTnet\Server\MqttClientConnection.cs:line 155
2019-04-20 09:01:06.1057  INFO MqttClientConnection Client '74aa5490-12c3-4810-85fb-eec5bbd50b85': Session stopped.

**Comment by chkr1011** [comment]
Do you have a longer snipped maybe? There is a reason then the socket is disposed from another thread but then I would expect another exception in the logs before.

**Comment by chkr1011** [comment]
Please try again with latest dev branch. I improved the connection handling so that at least further connections should work after an exception. This should not block new clients any longer.

I also added new logs. So please share them as soon as they appear.

**Comment by biovoid** [comment]
> Do you have a longer snipped maybe? There is a reason then the socket is disposed from another thread but then I would expect another exception in the logs before.

Longer logs just contains receiving messages, no non-standard behavior.

> Please try again with latest dev branch. I improved the connection handling so that at least further connections should work after an exception. This should not block new clients any longer.

Ok

**Comment by biovoid** [comment]
Not the latest dev branch, but after I get the MqttCommunicationException the device shows that it was connected and (i am checking) was publishing message, but can't receive any subscribtions. The log shows that session was stopped. And after there are not messages from this clientId in the log, but my device had connection to the server. Also this bug can be on my side. 
Is there any chance that client session was "detached" and floating with active socket connection?
Also I will try a newer version of dev branch.

```
2019-04-22 10:19:16.3276  WARN MqttClientKeepAliveMonitor Client '44658ba7-cd53-4bdc-8fe2-c5c9031ac3a7': Did not receive any packet or keep alive signal.
2019-04-22 10:19:16.3276  WARN MqttClientConnection Client '44658ba7-cd53-4bdc-8fe2-c5c9031ac3a7': Communication exception while receiving client packets.MQTTnet.Exceptions.MqttCommunicationException: Cannot access a disposed object.
Object name: 'SslStream'. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.get_SecureStream()
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.MqttTcpChannel.<ReadAsync>d__14.MoveNext() in C:\Repositories\project\MQTTnet\Source\MQTTnet\Implementations\MqttTcpChannel.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Formatter.MqttPacketReader.<ReadFixedHeaderAsync>d__3.MoveNext() in C:\Repositories\project\MQTTnet\Source\MQTTnet\Formatter\MqttPacketReader.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceiveAsync>d__35.MoveNext() in C:\Repositories\project\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 211
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in C:\Repositories\project\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 158
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception) in C:\Repositories\project\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 315
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__33.MoveNext() in C:\Repositories\project\MQTTnet\Source\MQTTnet\Adapter\MqttChannelAdapter.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MQTTnet.Server.MqttClientConnection.<RunInternalAsync>d__29.MoveNext() in C:\Repositories\project\MQTTnet\Source\MQTTnet\Server\MqttClientConnection.cs:line 155
2019-04-22 10:19:16.3276  INFO MqttClientConnection Client '44658ba7-cd53-4bdc-8fe2-c5c9031ac3a7': Session stopped.

**Comment by chkr1011** [comment]
Please check if the client and session status APIs give proper results. It should be impossible that a client is connected but not listet at the GetClientStatus API.

**Comment by biovoid** [comment]
Test that and latest builds, seems its ok now with secure connection.
