### ISSUE TITLE
Exception publishing message from server side

### ISSUE THREAD

**Issue by biovoid** [chkr1011/MQTTnet#598]
I'm trying to PublishAsync a message in the HandleClientConnectedAsync method. This method execute without any problem. But when message starts publish I see an exception

```
2019-04-22 18:08:15.2229  INFO MqttClientConnection Client '40fbc2ad-2634-4017-b37f-194335d4aca1': Session started.
2019-04-22 18:08:15.2229 ERROR MqttClientSessionsManager Unhandled exception while processing next queued application message.System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.GenericEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at NLog.LogFactory.LoggerCache.Retrieve(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at KomfortIQ.Server.<InterceptApplicationMessagePublishAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Server.MqttClientSessionsManager.<InterceptApplicationMessageAsync>d__25.MoveNext() in C:\Repositories\project\MQTTnet\Source\MQTTnet\Server\MqttClientSessionsManager.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Server.MqttClientSessionsManager.<TryProcessNextQueuedApplicationMessageAsync>d__21.MoveNext() in C:\Repositories\project\MQTTnet\Source\MQTTnet\Server\MqttClientSessionsManager.cs:line 184
2019-04-22 18:08:15.5119  INFO 40fbc2ad-2634-4017-b37f-194335d4aca1 Publishing from Thermostat (480032000e51363136333630)

**Comment by chkr1011** [comment]
Please provide a small code snipped to I can try to reproduce it locally.

**Comment by biovoid** [comment]
```
public class NLogChildLogger : IMqttNetChildLogger
{
    private readonly Logger logger;

    public NLogChildLogger(string source)
    {
        if (String.IsNullOrEmpty(source))
            logger = LogManager.GetCurrentClassLogger();
        else
            logger = LogManager.GetLogger(source);
    }

    public IMqttNetChildLogger CreateChildLogger(string source = null)
    {
        return new NLogChildLogger(source);
    }

    public void Error(Exception exception, string message, params object[] parameters)
    {
        if (exception != null)
            logger.Error(exception, message, parameters);
        else
            logger.Error(message, parameters);
    }

    public void Info(string message, params object[] parameters)
    {
        logger.Info(message, parameters);
    }
    
    public void Verbose(string message, params object[] parameters)
    {
        logger.Trace(message, parameters);
    }

    public void Warning(Exception exception, string message, params object[] parameters)
    {
        if (exception != null)
            logger.Warn(exception, message, parameters);
        else
            logger.Warn(message, parameters);
    }
}

public class NLogLogger : IMqttNetLogger
{
    public event EventHandler<MqttNetLogMessagePublishedEventArgs> LogMessagePublished;

    public IMqttNetChildLogger CreateChildLogger(string source = null)
    {
        return new NLogChildLogger(source);
    }

    public void Publish(MqttNetLogLevel logLevel, string source, string message, object[] parameters, Exception exception)
    {
        LogMessagePublished?.Invoke(this, null);
    }
}

...

public class Server : IMqttServerClientConnectedHandler
{
    private readonly IMqttServer mqttServer;

    public Server(IMqttServer server)
    {
        mqttServer = server;
    }

    public async Task HandleClientConnectedAsync(MqttServerClientConnectedEventArgs eventArgs)
    {
        await mqttServer.PublishAsync("/test/1", "true", MqttQualityOfServiceLevel.ExactlyOnce, false);
    }
}

...

static async Task RunServer()
{
    IMqttServer mqttServer = new MqttFactory().CreateMqttServer(new NLogLogger());
    Server server = new Server(mqttServer);

    X509Certificate2 certificate = new X509Certificate2(@"cert.pfx", "", X509KeyStorageFlags.Exportable);
    MqttServerOptions options = new MqttServerOptions();
    options.TlsEndpointOptions.Certificate = certificate.Export(X509ContentType.Pfx);
    options.TlsEndpointOptions.IsEnabled = true;
                
    mqttServer.ClientConnectedHandler = server;

    await mqttServer.StartAsync(options);
}

**Comment by chkr1011** [comment]
I added UnitTest _Publish_After_Client_Connects_ in dev branch. It works without problems. Am I missing something?

**Comment by JanEggers** [comment]
the stack is in NLog.LogFactory so either add locking or post an issue in their repo

**Comment by biovoid** [comment]
Oh, missed that lines about NLog. Sorry.

**Comment by biovoid** [comment]
I've tested latest build and I remove my logger from NLogChildLogger. But the problem is not solved, I mean that I call PublishAsync and its result is MqttClientPublishReasonCode.Success, but nobody receives a message with QoS 2 and retain=true.

**Comment by chkr1011** [comment]
Please check UnitTest _Publish_After_Client_Connects_ and modify it so it fails.

**Comment by biovoid** [comment]
I found a problem. When server use clients API like PublishAsync the ClientId inside InterceptApplicationMessagePublishAsync is null. I didn't handle null for ClientId, thats why it generates an exception. Was not obvious for me, may be its better to setup predefined or users ClientId for server role.

**Comment by chkr1011** [comment]
Ah OK that makes sense. Yes the ClientId is null because the server has no ClientId in that case. I was tinking about using "server" or similar but this may conflict with ClientIds in a project where "server" is a real client.

**Comment by biovoid** [comment]
I think it will be nice if you make a property and let user setup it. By default it can be null.

**Comment by chkr1011** [comment]
I pushed that. It is part of the server options and server options builder. Please let me know if this works for you.
