### ISSUE TITLE
ObjectDisposedException for SSL

### ISSUE THREAD

**Issue by gregjesl** [chkr1011/MQTTnet#611]
## Environment
Using Nuget release `3.0.0-rc2` on a Windows 10 Virtual Machine hosted by Microsoft Azure.  

The client device is an ESP32 connecting using TCP and TLS (SSL).  

I see that `3.0.0` was just released, I'll update my program and see if I see the issue again.  

## Background
First and foremost, thank you for this library.  

I'm hosting an MQTT broker that supports SSL.  I implemented a loopback test because I've noticed that the broker will sometimes stop accepting new SSL clients (unfortunately I don't have any more information regarding that issue).  I have a client that connects every minute over SSL, subscribes to a loopback topic, publishes a message, and then ensures that the message was received.  If the message was not received, then the broker is shut down and restarted.  

## Issue
During a restart triggered by the loopback discussed above, the following exception occurred:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> 
  MQTTnet.Exceptions.MqttCommunicationException: The write operation failed, see inner exception. ---> 
  System.IO.IOException: The write operation failed, see inner exception. ---> 
  System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.<WriteAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Internal.MqttTaskTimeout.<WaitAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Adapter.MqttChannelAdapter.<SendPacketAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.<SendPacketAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<DisconnectAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MQTTnet.Client.MqttClient.<DisconnectAsync>d__34.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DeviceMQTTServer.Program.Main(String[] args)
```

**Comment by chkr1011** [comment]
Hi, 
thank you for reporting this issue. Could you please try again with 3.0.2?
Best regards
Christian

**Comment by gregjesl** [comment]
I just checked the broker (using v3.0.0) which has been running for a few days.  I haven't seen the issue in a while.  I'll close this issue and re-open it if I see the issue again.
