### ISSUE TITLE
ManagedClient not catch NotAuthorized exception

### ISSUE THREAD

**Issue by setamodius** [chkr1011/MQTTnet#619]
I am trying to catch NotAuthorized exception. I see it on trace but in 'UseDisconnectedHandler' exception is null.
My broker is emqx 3.1.1

Code;
```
static void Main(string[] args)
        {
            var mqttClient = new MqttFactory().CreateManagedMqttClient(); 
            
            var options = new ManagedMqttClientOptionsBuilder()
                 .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                 .WithClientOptions(new MqttClientOptionsBuilder()
                    .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V311)
                    .WithClientId("Client1")
                    .WithTcpServer("10.3.4.16",1883)
                    .WithCredentials("master","test")
                    .WithCleanSession())
                 .Build();

            mqttClient.UseDisconnectedHandler(e =>
            {
                Console.WriteLine("Error:" + e.Exception?.ToString());                
            });

            MqttNetGlobalLogger.LogMessagePublished += (s, e) =>
            {
                var trace = $">> [{e.TraceMessage.Timestamp:O}] [{e.TraceMessage.ThreadId}] [{e.TraceMessage.Source}] [{e.TraceMessage.Level}]: {e.TraceMessage.Message}";
                if (e.TraceMessage.Exception != null)
                {
                    trace += Environment.NewLine + e.TraceMessage.Exception.ToString();
                }

                Console.WriteLine(trace);
            };

            mqttClient.StartAsync(options);
            
            Console.ReadLine();
        }    
```

Trace;
```
>> [2019-05-09T12:49:13.8995819Z] [1] [ManagedMqttClient] [Info]: Started
>> [2019-05-09T12:49:13.9290131Z] [3] [MqttClient] [Verbose]: Trying to connect with server '10.3.4.16:1883' (Timeout=00:00:10).
>> [2019-05-09T12:49:14.0350436Z] [6] [MqttClient] [Verbose]: Connection with server established.
>> [2019-05-09T12:49:14.0426323Z] [4] [MqttClient] [Verbose]: Start receiving packets.
>> [2019-05-09T12:49:14.0745740Z] [6] [MqttClient.MqttChannelAdapter] [Verbose]: TX (35 bytes) >>> Connect: [ClientId=Client1] [Username=master] [Password=****] [KeepAlivePeriod=15] [CleanSession=True]
>> [2019-05-09T12:49:14.0966254Z] [7] [MqttClient.MqttChannelAdapter] [Verbose]: RX (4 bytes) <<< ConnAck: [ReturnCode=ConnectionRefusedNotAuthorized] [ReasonCode=] [IsSessionPresent=False]
>> [2019-05-09T12:49:14.1108304Z] [7] [MqttClient] [Verbose]: Disconnecting [Timeout=00:00:10]
>> [2019-05-09T12:49:14.1329771Z] [7] [MqttClient] [Verbose]: Disconnected from adapter.
>> [2019-05-09T12:49:14.1337442Z] [7] [MqttClient] [Info]: Disconnected.
Error:
>> [2019-05-09T12:49:14.1347252Z] [7] [MqttClient] [Verbose]: Stopped receiving packets.
>> [2019-05-09T12:49:14.1134378Z] [4] [MqttClient] [Error]: Error while connecting with server.
MQTTnet.Adapter.MqttConnectingFailedException: Connecting with MQTT server failed (NotAuthorized).
   at MQTTnet.Client.MqttClient.AuthenticateAsync(IMqttChannelAdapter channelAdapter, MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
>> [2019-05-09T12:49:19.1849464Z] [8] [MqttClient] [Verbose]: Trying to connect with server '10.3.4.16:1883' (Timeout=00:00:10).
>> [2019-05-09T12:49:19.1890126Z] [7] [MqttClient] [Verbose]: Connection with server established.
>> [2019-05-09T12:49:19.1897009Z] [8] [MqttClient] [Verbose]: Start receiving packets.
>> [2019-05-09T12:49:19.1900141Z] [7] [MqttClient.MqttChannelAdapter] [Verbose]: TX (35 bytes) >>> Connect: [ClientId=Client1] [Username=master] [Password=****] [KeepAlivePeriod=15] [CleanSession=True]
>> [2019-05-09T12:49:19.1930085Z] [7] [MqttClient.MqttChannelAdapter] [Verbose]: RX (4 bytes) <<< ConnAck: [ReturnCode=ConnectionRefusedNotAuthorized] [ReasonCode=] [IsSessionPresent=False]
>> [2019-05-09T12:49:19.1940417Z] [7] [MqttClient] [Verbose]: Disconnecting [Timeout=00:00:10]
>> [2019-05-09T12:49:19.1949367Z] [7] [MqttClient] [Verbose]: Disconnected from adapter.
>> [2019-05-09T12:49:19.1954235Z] [7] [MqttClient] [Info]: Disconnected.
Error:
>> [2019-05-09T12:49:19.1949508Z] [8] [MqttClient] [Error]: Error while connecting with server.
MQTTnet.Adapter.MqttConnectingFailedException: Connecting with MQTT server failed (NotAuthorized).
   at MQTTnet.Client.MqttClient.AuthenticateAsync(IMqttChannelAdapter channelAdapter, MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
>> [2019-05-09T12:49:19.2011984Z] [7] [MqttClient] [Verbose]: Stopped receiving packets.

```

**Comment by chkr1011** [comment]
Hi,
I added this to the regular client disconnected event args. But it is not set if the disconnect is initiated by the user or due to an exception or connection failure.
Best regards
Christian

**Comment by setamodius** [comment]
Thanks for fast response.
How can i detect NotAuthorized connection?
Thanks

**Comment by chkr1011** [comment]
I don't know what you mean.

**Comment by setamodius** [comment]
Hi,
I am trying to connect with wrong credentials for testing. But 'MqttClientDisconnectedEventArgs' is giving me only one value. ClientWasConnected= false,' Exception' and 'AuthenticateResult' are null. How can i get "NotAuthorized" message?

**Comment by SeppPenner** [comment]
@chkr1011 I guess, @setamodius wants to get a `NotAuthorized` exception when the credentials are wrong, not the `ClientWasConnected=false` property (only).

**Comment by chkr1011** [comment]
@setamodius Which version are you using? I remember that something in that area was changed some month ago.

**Comment by setamodius** [comment]
I tested it with v3.0.5. But it is not working.

**Comment by SeppPenner** [comment]
@setamodius Just again: What do you want to achieve? Catching the exception properly?

**Comment by setamodius** [comment]
Yes. I am trying to catch "NotAuthorized" exception.

**Comment by chkr1011** [comment]
Oh you are using the ManageClient... At the moment this is not supported here. Maybe you can switch to the regular client instead?

**Comment by setamodius** [comment]
Ok. I will switch to regular client. 
Thanks
