### ISSUE TITLE
 TCP address reuse does not work on linux

### ISSUE THREAD

**Issue by nesherhh** [chkr1011/MQTTnet#679]
3.0.4 introduced "[Server] The TCP address is now reused when starting which should prevent "port in used" error when restarting."
This throws exception on linux:

> System.Net.Sockets.SocketException : Permission denied
Stack Trace: 
at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName) 
at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent) 
at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue) 
at MQTTnet.Implementations.MqttTcpServerListener.Start(Boolean treatErrorsAsWarning, CancellationToken cancellationToken) 
at MQTTnet.Implementations.MqttTcpServerAdapter.RegisterListeners(MqttServerTcpEndpointBaseOptions options, X509Certificate2 tlsCertificate, CancellationToken cancellationToken) 
at MQTTnet.Implementations.MqttTcpServerAdapter.StartAsync(IMqttServerOptions options) 
at MQTTnet.Server.MqttServer.StartAsync(IMqttServerOptions options)

**Comment by chkr1011** [comment]
Does it also fail when using an admin account?

**Comment by nesherhh** [comment]
Yes. sudo dotnet test runs ok. But it should also run in Azure DevOps CI without admin account.

**Comment by chkr1011** [comment]
Ok you are right. I just want to understand that issue first. I will move that setting to the options instead.

**Comment by chkr1011** [comment]
I released 3.0.5. The setting is now moved to the options and off by default. So when this is needed/possible then it should be activated.

**Comment by VladimirAkopyan** [comment]
I have what appears to be the same issue when deploying container in Azure AKS Kubernetes service, but from this conversation  I can't quite understand what's happening. I have version 3.0.5. 
Could you explain a bit more what is this option?

**Comment by SeppPenner** [comment]
@chkr1011 This is something you need to explain.

**Comment by chkr1011** [comment]
@VladimirAkopyan I also have no clear understanding. I just implemented that based on a recommendation from another user.

But what I found is that a socket is still "open" when the application is closed. This is related to the clients which are still connected and the OS will keep the socket "alive" for some time to let the clients disconnect properly (sending FIN, ACK whatever TCP stuff). When restarting the MQTT server in a short time the socket is still "in use" by the OS waiting for disconnect ACK of the clients. Here the setting comes in and requests to the OS that we want to get the already existing socket back. The drawback is that we might get some data on that socket. But this is not a problem because we are hosting the same MQTT server on that port. If the socket was used by another application it might be not a good idea to take over that existing socket. Then the exception is welcome instead. 

On linux this takeover of the socket requires admin rights.

I hope that is more or less correct. I someone else has more details please share.

**Comment by GameBelial** [comment]
@chkr1011 I also had this problem,so I still used version 3.0.2.

**Comment by GameBelial** [comment]
exception:
```
Unhandled Exception: System.Net.Sockets.SocketException: Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at MQTTnet.Implementations.MqttTcpServerListener.Start(Boolean treatErrorsAsWarning, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpServerAdapter.RegisterListeners(MqttServerTcpEndpointBaseOptions options, X509Certificate2 tlsCertificate, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpServerAdapter.StartAsync(IMqttServerOptions options)
   at MQTTnet.Server.MqttServer.StartAsync(IMqttServerOptions options)
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
```

code:
```
        public static void Main(string[] args)
        {
            //CreateWebHostBuilder(args).Build().Run();
            var mqttOptionBuilder = new MqttServerOptionsBuilder()
                .WithConnectionBacklog(100)
                .WithDefaultEndpointBoundIPAddress(IPAddress.Parse("0.0.0.0"))
                .WithDefaultEndpointPort(35001);
            
            var _mqttServer = new MqttFactory().CreateMqttServer();
            AsyncHelper.RunSync(()=>_mqttServer.StartAsync(mqttOptionBuilder.Build()));
        }
```
My operating system is centos 7.x,I can reproduce it in the Docker container.

**Comment by chkr1011** [comment]
You have to upgrade to 3.0.5. The fix is only there.
