### ISSUE TITLE
Unit test MqttServer_PublishSimple_ExactlyOnce fails

### ISSUE THREAD

**Issue by Zazzmatazz** [chkr1011/MQTTnet#7]
Test Name:	MqttServer_PublishSimple_ExactlyOnce
Test FullName:	MQTTnet.Core.Tests.MqttServerTests.MqttServer_PublishSimple_ExactlyOnce
Test Source:	C:\Users\Zazzmatazz\Documents\Visual Studio 2017\Projects\MQTTnet-master\Tests\MQTTnet.Core.Tests\MqttServerTests.cs : line 40
Test Outcome:	Failed
Test Duration:	0:00:02.632876

Result StackTrace:	
at MQTTnet.Core.Tests.MqttServerTests.<TestPublishAsync>d__5.MoveNext() in C:\Users\Zazzmatazz\Documents\Visual Studio 2017\Projects\MQTTnet-master\Tests\MQTTnet.Core.Tests\MqttServerTests.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Core.Tests.MqttServerTests.<MqttServer_PublishSimple_ExactlyOnce>d__2.MoveNext() in C:\Users\Zazzmatazz\Documents\Visual Studio 2017\Projects\MQTTnet-master\Tests\MQTTnet.Core.Tests\MqttServerTests.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Result Message:	Assert.AreEqual failed. Expected:<1>. Actual:<0>.

**Comment by chkr1011** [comment]
Hi,
yes I will have a look at it.

Best regards
Christian

**Comment by chkr1011** [comment]
This is fixed in release 2.1.5...
