### ISSUE TITLE
Publish function normal MQTT client not working

### ISSUE THREAD

**Issue by martinj2001** [chkr1011/MQTTnet#710]
### Describe the bug
I want to publish using the code featured on the wiki, but that doesn't work...

### Which project is your bug related to?
- [x] Client
- [ ] ManagedClient
- [ ] MQTTnet.Server standalone
- [ ] Server
- [ ] Generic

```csharp
private static async void subscribe()
        {
            options = new MqttClientOptionsBuilder()
                .WithClientId("Client C#")
                .WithTcpServer(brokerId, brokerPort)
                .Build();

            factory = new MqttFactory();
            mqttClient = factory.CreateMqttClient();
            await mqttClient.ConnectAsync(options);
            await mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic("#").Build());

            mqttClient.UseApplicationMessageReceivedHandler(e =>
            {
                //Console lines for debugging purposes
                //
                Console.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
                Console.WriteLine($"Topic = {e.ApplicationMessage.Topic}");
                Console.WriteLine($"Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
                Console.WriteLine($"QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
                Console.WriteLine($"Retain = {e.ApplicationMessage.Retain}");
                Console.WriteLine();
                string messageTopic = e.ApplicationMessage.Topic;
                if (tags.TryGetValue(messageTopic, out string topicString))
                {
                    items.Enqueue(Encoding.UTF8.GetString(e.ApplicationMessage.Payload) + "," + topicString);
                }
                    //The received message gets queued in the items queue
                    //
                

            });

            mqttClient.UseDisconnectedHandler(async e =>
            {
                Console.WriteLine("### DISCONNECTED FROM SERVER ###");
                await Task.Delay(TimeSpan.FromSeconds(5));

                try
                {
                    await mqttClient.ConnectAsync(options);
                }
                catch
                {
                    Console.WriteLine("### RECONNECTING FAILED ###");
                }
            });
        }
```

This is the subscribe function. This is the publish function: 

```csharp
private static async void publish()
        {

            message = new MqttApplicationMessageBuilder()
                .WithTopic(topic)
                .WithPayload(payload + generateRandom(10, 20))
                .WithExactlyOnceQoS()
                .WithRetainFlag()
                .Build();

            try
            {
                await mqttClient.PublishAsync(message);
                await mqttClient.PublishAsync(message);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
       }
```

When I run the publish function after the subscribe function I get the exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: client
   at MQTTnet.Client.MqttClientExtensions.PublishAsync(IMqttClient client, MqttApplicationMessage applicationMessage)
   at mqttConnector.connector.<publish>d__24.MoveNext() in C:\Users\Martin\OneDrive\Documenten\mqttConnector\mqttConnector\mqttConnector\connector.cs:line 367

**Comment by SeppPenner** [comment]
For me, this looks like you do not set the `mqttClient` object to a value other than `null` before you want to use it. As this is somewhere in your global variables (or whatever), I can't see where the issue is exactly.

**Comment by martinj2001** [comment]
Dear Hans,

I found the issue! The publish thread started before the subscribe thread.
This meant that the client was not connected yet!

Thanks for your help!

Best regards,

Martin
