### ISSUE TITLE
SocketException: Permission denied on Ubuntu 18.04 with default ports

### ISSUE THREAD

**Issue by Slaviusz** [chkr1011/MQTTnet#720]
### Describe the bug
When starting .Net Core 2.2 application
On freshly installed and patched Ubuntu 18.04 Linux
As an unprivileged linux user
With both TCP and TLS default ports configured
Application crashes with:

> Unhandled Exception: System.Net.Sockets.SocketException: Permission denied

### Which project is your bug related to?
- [ ] Client
- [ ] ManagedClient
- [x] MQTTnet.Server standalone
- [ ] Server
- [ ] Generic

### To Reproduce
1. Using this version of MQTTnet '3.0.5'.
2. Run this code 'See code below'.
3. With these arguments 'dotnet run'.
4. See error.

### Expected behavior
Application starts up correctly.

### Screenshots
Not applicable.

### Additional context / logging
```
mqtt@Ubuntu18.04:~/mqtt_server$ dotnet run
Environment: Development

Unhandled Exception: System.Net.Sockets.SocketException: Permission denied
at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
at MQTTnet.Implementations.MqttTcpServerListener.Start(Boolean treatErrorsAsWarning, CancellationToken cancellationToken)
at MQTTnet.Implementations.MqttTcpServerAdapter.RegisterListeners(MqttServerTcpEndpointBaseOptions options, X509Certificate2 tlsCertificate, CancellationToken cancellationToken)
at MQTTnet.Implementations.MqttTcpServerAdapter.StartAsync(IMqttServerOptions options)
at MQTTnet.Server.MqttServer.StartAsync(IMqttServerOptions options)
at mqtt_server.Program.Main() in /home/mqtt/iot/mqtt_server/Program.cs:line 58
at mqtt_server.Program.<Main>()
```

```
mqtt@Ubuntu18.04:~/mqtt_server$ strace -f -s 20 -e trace=%network dotnet run -c Debug
strace: Process 2451 attached
strace: Process 2452 attached

...

Environment: Development
strace: Process 2514 attached
strace: Process 2515 attached
strace: Process 2516 attached
strace: Process 2517 attached
strace: Process 2518 attached
strace: Process 2519 attached
[pid  2503] socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 100
[pid  2503] setsockopt(100, SOL_SOCKET, SO_DEBUG, [1], 4) = -1 EACCES (Permission denied)

Unhandled Exception: System.Net.Sockets.SocketException: Permission denied
...
```
### Code example
```csharp
var certificate = new X509Certificate2(@"certificate.pfx", "[REDACTED]", X509KeyStorageFlags.Exportable);

var optionsBuilder = new MqttServerOptionsBuilder()
		  .WithDefaultEndpointPort(1883)
		  .WithEncryptedEndpoint()
		  .WithEncryptedEndpointPort(1884)
		  .WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx))
		  .WithEncryptionSslProtocol(SslProtocols.Tls12)
		  .WithPersistentSessions()
		  .WithConnectionBacklog(100)
		  .WithApplicationMessageInterceptor(async context => {
			  // handler code
			  }
		  })
		  .WithMaxPendingMessagesPerClient(3)
		  .WithConnectionBacklog(100)
		  .WithStorage(new RetainedMessageHandler())
		  .WithDefaultCommunicationTimeout(TimeSpan.FromMinutes(5))
	 ;

var mqttServer = new MqttFactory().CreateMqttServer();
await mqttServer.StartAsync(optionsBuilder.Build());
...
```

**Comment by ikalkov** [comment]
I had to update our MQTTnet package to the latest version because of another issue (#719) and faced the same problem just a minute ago!

**Comment by chkr1011** [comment]
This is fixed in 3.0.6. So you can either wait for that version or use the latest beta.

**Comment by ikalkov** [comment]
Awesome, thanks for the super fast fix!

**Comment by ikalkov** [comment]
@chkr1011, is there a timeline or ETA for 3.0.6?

**Comment by chkr1011** [comment]
I will release the new version this weekend.
