### ISSUE TITLE
Several MqttException and then no message is sent

### ISSUE THREAD

**Issue by bricegomis** [chkr1011/MQTTnet#738]
### Describe the bug
I use a IManagedMqttClient. After a while, I have a lot of Exception when sending messages and I have to restart the application.

### Which project is your bug related to?
- ManagedClient

### To Reproduce
1. Using this version of MQTTnet '2.8.5 or 3.0.5'.
2. Run this code ' Send several messages to a topic already subscribed.'
4. See error.

### Expected behavior
No exception

### Additional context / logging

```bash
PRESS ENTER TO FINISH
OnMqttClientConnected
.................................................MqttNetLog >> [2019-08-09T08:56:43.4370955Z] [11] [MqttClient] [Warning]: MQTT communication exception while receiving packets.
MQTTnet.Exceptions.MqttCommunicationException: Expected at least 35 bytes but there are only 2 bytes
Parameter name: _buffer ---> System.ArgumentOutOfRangeException: Expected at least 35 bytes but there are only 2 bytes
Parameter name: _buffer
   at MQTTnet.Formatter.MqttPacketBodyReader.ReadSegmentWithLengthPrefix()
   at MQTTnet.Formatter.MqttPacketBodyReader.ReadStringWithLengthPrefix()
   at MQTTnet.Formatter.V3.MqttV310PacketFormatter.DecodePublishPacket(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Formatter.V3.MqttV310PacketFormatter.Decode(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Formatter.MqttPacketFormatterAdapter.Decode(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__35.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<TryReceivePacketsAsync>d__48.MoveNext()
MqttNetLog >> [2019-08-09T08:56:43.4458851Z] [5] [ManagedMqttClient] [Warning]: Publishing application (81395b4e-ace9-4855-904f-795492c13389) message failed.
MQTTnet.Exceptions.MqttCommunicationException: Expected at least 35 bytes but there are only 2 bytes
Parameter name: _buffer ---> System.ArgumentOutOfRangeException: Expected at least 35 bytes but there are only 2 bytes
Parameter name: _buffer
   at MQTTnet.Formatter.MqttPacketBodyReader.ReadSegmentWithLengthPrefix()
   at MQTTnet.Formatter.MqttPacketBodyReader.ReadStringWithLengthPrefix()
   at MQTTnet.Formatter.V3.MqttV310PacketFormatter.DecodePublishPacket(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Formatter.V3.MqttV310PacketFormatter.Decode(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Formatter.MqttPacketFormatterAdapter.Decode(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__35.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.<ReceivePacketAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<TryReceivePacketsAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<PublishAtLeastOnceAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.<TryPublishQueuedMessageAsync>d__58.MoveNext()
OnMqttClientDisconnected
OnMqttClientConnected
....................................................................................................................=========================================
MqttNetLog >> [2019-08-09T08:56:55.1322950Z] [15] [ManagedMqttClient] [Warning]: Publishing application (19a50250-9059-4c16-9b9d-af53eab36b8b) message failed.
MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<PublishAtLeastOnceAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.<TryPublishQueuedMessageAsync>d__58.MoveNext()
MqttNetLog >> [2019-08-09T08:56:55.1430345Z] [8] [MqttClient] [Error]: Unhandled exception while receiving packets.
MQTTnet.Exceptions.MqttProtocolViolationException: Received packet 'PubComp: [PacketIdentifier=116] [ReasonCode=]' at an unexpected time.
   at MQTTnet.PacketDispatcher.MqttPacketDispatcher.Dispatch(MqttBasePacket packet)
   at MQTTnet.Client.MqttClient.<TryProcessReceivedPacketAsync>d__49.MoveNext()
MqttNetLog >> [2019-08-09T08:56:55.1498735Z] [5] [ManagedMqttClient] [Error]: Unhandled exception while publishing application message (19a50250-9059-4c16-9b9d-af53eab36b8b).
MQTTnet.Exceptions.MqttProtocolViolationException: Received packet 'PubComp: [PacketIdentifier=116] [ReasonCode=]' at an unexpected time.
   at MQTTnet.PacketDispatcher.MqttPacketDispatcher.Dispatch(MqttBasePacket packet)
   at MQTTnet.Client.MqttClient.<TryProcessReceivedPacketAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<PublishAtLeastOnceAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.<TryPublishQueuedMessageAsync>d__58.MoveNext()
OnMqttClientDisconnected
OnMqttClientConnected
.............................................................................................................................................=========================================
MqttNetLog >> [2019-08-09T08:57:07.2378978Z] [5] [ManagedMqttClient] [Warning]: Publishing application (cf2018ee-64be-434a-b8c1-063e52e4ee66) message failed.
MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<PublishAtLeastOnceAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.<TryPublishQueuedMessageAsync>d__58.MoveNext()
=========================================
MqttNetLog >> [2019-08-09T08:57:17.2535112Z] [23] [ManagedMqttClient] [Warning]: Publishing application (cf2018ee-64be-434a-b8c1-063e52e4ee66) message failed.
MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<PublishAtLeastOnceAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.<TryPublishQueuedMessageAsync>d__58.MoveNext()
MqttNetLog >> [2019-08-09T08:57:17.2662038Z] [9] [MqttClient] [Error]: Unhandled exception while receiving packets.
MQTTnet.Exceptions.MqttProtocolViolationException: Received packet 'PubComp: [PacketIdentifier=29556] [ReasonCode=]' at an unexpected time.
   at MQTTnet.PacketDispatcher.MqttPacketDispatcher.Dispatch(MqttBasePacket packet)
   at MQTTnet.Client.MqttClient.<TryProcessReceivedPacketAsync>d__49.MoveNext()
MqttNetLog >> [2019-08-09T08:57:17.2740146Z] [11] [ManagedMqttClient] [Error]: Unhandled exception while publishing application message (cf2018ee-64be-434a-b8c1-063e52e4ee66).
MQTTnet.Exceptions.MqttProtocolViolationException: Received packet 'PubComp: [PacketIdentifier=29556] [ReasonCode=]' at an unexpected time.
   at MQTTnet.PacketDispatcher.MqttPacketDispatcher.Dispatch(MqttBasePacket packet)
   at MQTTnet.Client.MqttClient.<TryProcessReceivedPacketAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<PublishAtLeastOnceAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.<TryPublishQueuedMessageAsync>d__58.MoveNext()
OnMqttClientDisconnected
OnMqttClientConnected
.................................................................=========================================
MqttNetLog >> [2019-08-09T08:57:28.5801855Z] [11] [ManagedMqttClient] [Warning]: Publishing application (ab188ea4-bf2a-4921-baf6-41cbc566176f) message failed.
MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<PublishAtLeastOnceAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.<TryPublishQueuedMessageAsync>d__58.MoveNext()
MqttNetLog >> [2019-08-09T08:57:28.5955264Z] [7] [MqttClient] [Error]: Unhandled exception while receiving packets.
MQTTnet.Exceptions.MqttProtocolViolationException: Received packet 'PubComp: [PacketIdentifier=25958] [ReasonCode=]' at an unexpected time.
   at MQTTnet.PacketDispatcher.MqttPacketDispatcher.Dispatch(MqttBasePacket packet)
   at MQTTnet.Client.MqttClient.<TryProcessReceivedPacketAsync>d__49.MoveNext()
MqttNetLog >> [2019-08-09T08:57:28.6004032Z] [5] [ManagedMqttClient] [Error]: Unhandled exception while publishing application message (ab188ea4-bf2a-4921-baf6-41cbc566176f).
MQTTnet.Exceptions.MqttProtocolViolationException: Received packet 'PubComp: [PacketIdentifier=25958] [ReasonCode=]' at an unexpected time.
   at MQTTnet.PacketDispatcher.MqttPacketDispatcher.Dispatch(MqttBasePacket packet)
   at MQTTnet.Client.MqttClient.<TryProcessReceivedPacketAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.<WaitOneAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<SendAndReceiveAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Client.MqttClient.<PublishAtLeastOnceAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.<TryPublishQueuedMessageAsync>d__58.MoveNext()
OnMqttClientDisconnected
OnMqttClientConnected
......................................................................................................................................................................................................................
```

### Code example
 
```csharp
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using MQTTnet;
using MQTTnet.Client.Connecting;
using MQTTnet.Client.Disconnecting;
using MQTTnet.Client.Options;
using MQTTnet.Client.Receiving;
using MQTTnet.Diagnostics;
using MQTTnet.Exceptions;
using MQTTnet.Extensions.ManagedClient;
using MQTTnet.Protocol;

namespace POC_MqttNetTimeOutException
{
    class Program
    {
        private static IManagedMqttClient _mqttClient;
        private static string _clientId = "123456789123456789";
        static void Main(string[] args)
        {
            _mqttClient = new MqttFactory().CreateManagedMqttClient();
            // Register events
            _mqttClient.ConnectedHandler = new MqttClientConnectedHandlerDelegate(OnMqttClientConnected);
            _mqttClient.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(OnMqttClientDisconnected);
            _mqttClient.ConnectingFailedHandler = new ConnectingFailedHandlerDelegate(OnMqttClientConnectingFailed);
            _mqttClient.ApplicationMessageReceivedHandler = new MqttApplicationMessageReceivedHandlerDelegate(OnMqttClientApplicationMessageReceived);
            _mqttClient.ApplicationMessageSkippedHandler = new ApplicationMessageSkippedHandlerDelegate(ApplicationMessageSkippedHandlerMethod);
            _mqttClient.ApplicationMessageProcessedHandler = new ApplicationMessageProcessedHandlerDelegate(ApplicationMessageProcessedHandlerMethod);
            MqttNetGlobalLogger.LogMessagePublished += (s, e) =>
            {
                var trace = $"MqttNetLog >> [{e.TraceMessage.Timestamp:O}] [{e.TraceMessage.ThreadId}] [{e.TraceMessage.Source}] [{e.TraceMessage.Level}]: {e.TraceMessage.Message}";
                if (e.TraceMessage.Exception != null)
                {
                    if (e.TraceMessage.Exception is MqttCommunicationTimedOutException)
                        Console.WriteLine("=========================================");
                    trace += Environment.NewLine + e.TraceMessage.Exception.ToString();
                    Console.WriteLine(trace);
                }
            };

            Task.Run(MainAsync);

            Console.WriteLine("PRESS ENTER TO FINISH");
            Console.ReadLine();
        }

        private static async Task MainAsync()
        {
            var mqttClientOptions = new ManagedMqttClientOptionsBuilder()
                .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                .WithClientOptions(new MqttClientOptionsBuilder()
                    .WithClientId(Guid.NewGuid().ToString())
                    .WithTls(new MqttClientOptionsBuilderTlsParameters
                    {
                        UseTls = true,
                        AllowUntrustedCertificates = true,
                        IgnoreCertificateChainErrors = true,
                        IgnoreCertificateRevocationErrors = true,
                    })
                    .WithTcpServer("192.168.10.147", 8883)
                    .WithCleanSession()
                    .Build())
                .Build();
            try
            {
                await _mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic($"prefix/{_clientId}/#").WithExactlyOnceQoS().Build());
                await _mqttClient.StartAsync(mqttClientOptions);

                var tasks = new Task[20];
                for (var i = 0; i < 20; i++)
                {
                    tasks[i] = StartClientFlood(i);
                }

                Task.WaitAll(tasks);
            }
            catch (Exception e)
            {
                Console.WriteLine("mqtt client start error " + e.Message);
            }
        }

        private static async Task StartClientFlood(int seed)
        {
                while (true)
                {
                    //Console.WriteLine(seed);
                    await Task.Delay(new Random(seed).Next(100, 500));
                    await _mqttClient.PublishAsync(new MqttApplicationMessage
                    {
                        Topic = $"prefix/{_clientId}/suffix" + seed,
                        Payload = Encoding.UTF8.GetBytes("test"),
                        QualityOfServiceLevel = MqttQualityOfServiceLevel.AtLeastOnce
                    }, CancellationToken.None);
                }
        }

        private static void ApplicationMessageProcessedHandlerMethod(ApplicationMessageProcessedEventArgs obj)
        {
            //Console.WriteLine("ApplicationMessageProcessedHandlerMethod");
        }

        private static void ApplicationMessageSkippedHandlerMethod(ApplicationMessageSkippedEventArgs obj)
        {
            Console.WriteLine("ApplicationMessageSkippedHandlerMethod");
        }

        private static void OnMqttClientApplicationMessageReceived(MqttApplicationMessageReceivedEventArgs obj)
        {
            Console.Write(".");
        }

        private static void OnMqttClientConnectingFailed(ManagedProcessFailedEventArgs obj)
        {
            Console.WriteLine("OnMqttClientConnectingFailed");
        }

        private static void OnMqttClientDisconnected(MqttClientDisconnectedEventArgs obj)
        {
            Console.WriteLine("OnMqttClientDisconnected");
        }

        private static void OnMqttClientConnected(MqttClientConnectedEventArgs obj)
        {
            Console.WriteLine("OnMqttClientConnected");
        }
    }
}
```

I made this sample project to test the latest version, I have the same behavior with the version 2.8.5.
Tell me if you need more information.

**Comment by bricegomis** [comment]
This seems to be related to being subscribed to the same topic as those sent, if I disable the subscription or subscribe to a specific topic instead of .../#, I have no more error.

**Comment by SeppPenner** [comment]
I'm not completely sure, but I might remember that this is something that is not yet supported by the managed client. @chkr1011?

**Comment by chkr1011** [comment]
To me it seems you are using the client from multiple tasks. The client is not thread safe. You have to lock it  using a SemaphoreSlim etc.

**Comment by SeppPenner** [comment]
> To me it seems you are using the client from multiple tasks. The client is not thread safe. You have to lock it using a SemaphoreSlim etc.

@bricegomis Can you confirm that, please?:

**Comment by bricegomis** [comment]
Yes that's right, we use it from different threads and as in my example. I naively believed that the client was safe thread. I will try with a SemaphoreSlim.
Thank you for your help and this library that saves time.

**Comment by SeppPenner** [comment]
If there are any futher questions, do not hesitate to ask us here :)
