### ISSUE TITLE
MqttCommunicationTimedOutException

### ISSUE THREAD

**Issue by det-iot** [chkr1011/MQTTnet#752]
### Describe the bug
I have an app in which the MQTT client have to publish several message to the destination MQTT broker.

To handle the message which the client hast to publish I use a `Parallel.ForEach`, so as I have seen in #738 this could be due the client is not thread safe

### Which project is your bug related to?

- Client

### To Reproduce
1. Using this version of MQTTnet 3.0.5

### Expected behavior
Publish the message without error

### Additional context / logging

```batch
Error en ManageMQTTClient: MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.WaitOneAsync(TimeSpan timeout)
at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
at MQTTnet.Client.MqttClient.PublishExactlyOnceAsync(MqttPublishPacket publishPacket, CancellationToken cancellationToken)
at x.MQTT.ManageMQTTClient(MQTTConfiguration MQTTconfigPublisher, String payload, ILogger`1 logger) in /app/MQTT.cs:line 50
```
### Code example
 
```csharp
Parallel.ForEach(receiveMessageResponse.Messages, async message =>
                            {
                                if (!string.IsNullOrEmpty(message.Body))
                                {
                                    try
                                    {
                                        await mqtt.ManageMQTTClient(MQTTconfigPublisher, message.Body,logger);                                      
                                    }
                                    catch (Exception e)
                                    {
                                        parallelExceptions.Enqueue(e);
                                    }
                                }
                           });


        public async Task ManageMQTTClient( MQTTConfiguration MQTTconfigPublisher, string payload, ILogger<Program> logger) 
        {
            string topic = "test";
            //string topic = payload.Split(";")[1];
            string cliente =  Guid.NewGuid().ToString();
            try
            {
                IMqttClientOptions optionsPublisher = new MqttClientOptionsBuilder()
                           .WithTcpServer(MQTTconfigPublisher.Servidor)
                            .WithClientId(cliente)
                            .WithCredentials(MQTTconfigPublisher.Username, MQTTconfigPublisher.Password)
                            .WithTls()
                            .WithCleanSession(false)
                            .WithKeepAlivePeriod(System.TimeSpan.FromSeconds(60))
                            .Build();

                IMqttClient mqttClientPublisher = new MqttFactory().CreateMqttClient();             
            
                mqttClientPublisher.UseConnectedHandler(async e =>
                {
                    try
                    {
                        logger.LogInformation("Cliente " + cliente + " conectado del servidor");
                        await mqttClientPublisher.PublishAsync(topic, payload.Split(";")[2], MQTTnet.Protocol.MqttQualityOfServiceLevel.ExactlyOnce);                        
                    }
                    catch (Exception ex)
                    {
                        throw;
                    }
                });

                mqttClientPublisher.UseDisconnectedHandler(async e =>
                {
                    logger.LogInformation("Cliente " + cliente + " desconectado del servidor. Intentando reconexion al broker: " + MQTTconfigPublisher.Servidor);
                    try
                    {
                        await mqttClientPublisher.ConnectAsync(optionsPublisher);
                        logger.LogInformation("Cliente " + cliente + " reconexion establecida con éxito al broker " + MQTTconfigPublisher.Servidor);
                    }
                    catch (Exception ex)
                    {
                        logger.LogError("Reconexión fallida al topic " + MQTTconfigPublisher.Topic + "  " + ex.Message);
                    }
                });

                await mqttClientPublisher.ConnectAsync(optionsPublisher);
            }
            catch (Exception ex)
            {
                throw;
            }
        }


```

--------------------------------------------------------

How should I deal with this problem? Should I use a simple foreach instead of parallel? 

Thank you.

**Comment by SeppPenner** [comment]
For me this looks valid on the first view. You're creating a client everytime you run it in a new task, so I would have expected it to work...
