### ISSUE TITLE
Mutual authentication with tls

### ISSUE THREAD

**Issue by liqiangno1** [chkr1011/MQTTnet#757]
### Describe your question
I have a mqtt broker like emqx，it support mutual authentication with tls,  I connect the broker successfully by using Mqtt.fx client software. but I don't known how to set the tls option with MQTTnet,  The wiki is also not clearly. Can you can help me?

The Mqtt.fx screenshot.
![image](https://user-images.githubusercontent.com/6667502/65367542-653fd300-dc65-11e9-8618-d922370dcaad.png)

### Which project is your question related to?

- Client
Mqttnet version: 3.0.5
Net core version: 2.2

**Comment by liqiangno1** [comment]
#115 #695 
I saw these issues , but still have no idea.

**Comment by liqiangno1** [comment]
` .WithTls(o =>
                {
                    o.UseTls = true;
                    o.Certificates = new List<byte[]>
                    {
                        new X509Certificate(@"C:/Users/liqia/Downloads/server/ca.pem", "").Export(X509ContentType.Cert),
                        new X509Certificate(@"C:\Users\liqia\Downloads\newclient\client.pfx", "").Export(X509ContentType.Cert)
                    };
                    o.CertificateValidationCallback = (x509Certificate, chain, sslPolicyErrors, mqttClientTcpOptions) => true;
                })`
I have generated the .pfx cert file and import them . and I received the fllowing exception

The message received was abnormal or incorrectly formatted

**Comment by SeppPenner** [comment]
You might take a look at this project: https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig/blob/b5159009f33e23b425313ac8cfcb361474c0688b/NetCoreMQTTExampleJsonConfig/Program.cs#L47. I'm using a certificate succssfully in there.

**Comment by robin-jones** [comment]
try `.Export(X509ContentType.SerializedCert)`

There is also a way to use the certs in their original pem and key format, but I am still working on a blog post for that!

**Comment by liqiangno1** [comment]
> You might take a look at this project: https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig/blob/b5159009f33e23b425313ac8cfcb361474c0688b/NetCoreMQTTExampleJsonConfig/Program.cs#L47. I'm using a certificate succssfully in there.

it's a server demo. but I need a client demo

**Comment by liqiangno1** [comment]
> try `.Export(X509ContentType.SerializedCert)`
> 
> There is also a way to use the certs in their original pem and key format, but I am still working on a blog post for that!

I run it successfully when I import the cert to windows certmgr.  but when run in linux system, it still has a exception.
`MQTTnet.Exceptions.MqttCommunicationException: Authentication failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
`
![image](https://user-images.githubusercontent.com/6667502/65572705-7c4f2f80-df9b-11e9-9b6a-8c70aa46fb33.png)

**Comment by SeppPenner** [comment]
> it's a server demo. but I need a client demo

Sorry, I misunderstood you here.

**Comment by SeppPenner** [comment]
This is also something to be documented once it works. I can do that if we find a solution.

**Comment by networkfusion** [comment]
So with my code, I can also connect to AWS on windows, but not on Linux. In my case I receive:

![image](https://user-images.githubusercontent.com/11439699/66602212-8aa76900-eba1-11e9-9933-fa09c31882d8.png)

I have a suspicion that both of these issues might be related to https://github.com/dotnet/corefx/issues/34740#

**Comment by EmanueleGiuliano** [comment]
Hi everyone, i'm facing a similar problem with my code. I found that on linux it doesn't send the certificate to the broker (i'm tring to make it work an aks), while on a windows VM it connects and reads messages.

here is my code:

` var mqttBrokerCertPubKey = new X509Certificate(cAcertificatePath);
            var mqttDmiClinetCert = new X509Certificate2(clientPfxCertificatePath, pfxPassword);
            
            //var mqttClientCert = new X509Certificate(clientCrtCertPath, "", X509KeyStorageFlags.Exportable);
            
            Console.WriteLine($"Configuration: topic-> ${topicSubscription}, clientId-> ${mqClientId}, address->${mqTcpAddress}, caPath->${cAcertificatePath}, certPath->${clientPfxCertificatePath}");
            
            var options = new ManagedMqttClientOptionsBuilder()
            .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
            .WithClientOptions(new MqttClientOptionsBuilder()
                        .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V311)
                        .WithClientId(mqClientId)
                        .WithTcpServer(mqTcpAddress, Configuration.GetValue<int>("port"))
                        .WithCommunicationTimeout(new TimeSpan(0, 2, 30))
                        .WithCleanSession()
                        .WithTls(new MqttClientOptionsBuilderTlsParameters()
                        {
                            UseTls = true,
                            AllowUntrustedCertificates = true,
                            Certificates = new[] { mqttBrokerCertPubKey.Export(X509ContentType.Cert), mqttDmiClinetCert.Export(X509ContentType.Pfx) },
                            IgnoreCertificateChainErrors = true,
                            IgnoreCertificateRevocationErrors = true,                             
                            SslProtocol = SslProtocols.None,
                            CertificateValidationCallback = (X509Certificate x, X509Chain y, SslPolicyErrors z, IMqttClientOptions o) =>
                            {

                                Console.WriteLine("Certificate--> issuer: " + x.Issuer + " subject: " + x.Subject);
                                return true;

                            }                            
                        })
                        .Build()
                )
            .Build();

            mqttClient = new MqttFactory().CreateManagedMqttClient();
            bool status = false;
            await mqttClient.StartAsync(options);

             mqttClient.ConnectingFailedHandler = new ConnectingFailedHandlerDelegate((ManagedProcessFailedEventArgs err)=>{
                Console.WriteLine("Error connecting to broker");
                Console.WriteLine(err.Exception.Message);
            });`

**Comment by robin-jones** [comment]
not sure if it helps, but I found that @networkfusion 's example works on Linux (using Docker) if I exclude the RootCA and set `IgnoreCertificateRevocationErrors = false` . Obviously you have to set the private cert and key as "Content" so that the docker image has them (probably a better way). I am guessing that it would be possible to to add the rootCA to the Linux key store so that it works as expected, but I haven't found a way yet...

**Comment by albigi** [comment]
we were able to understand the cause of the issue reported by @EmanueleGiuliano.
the client certificate we were passing to the MqttClientOptions was not trusted by our Linux containers, nor it was installed in the personal certificate store. Due to such limitations it was not being picked up during the TLS handshake upon receiving the list of supported trusted CAs from the broker endpoint.

bottomline, we solved the problem by adding the certificate to the cert store. we achieved this by running the lines below before configuring the MqttClient:

`using (var certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
{
    certStore.Open(OpenFlags.ReadWrite);
    var cert = new X509Certificate2(); //read the certificate from somewhere here
    certStore.Add(cert);
}`  

this solved out issues both on Linux and Windows.

At this stage I am wondering if installing the certificate in the personal store would make passing the certificate list to the MqttClientOptions useless (SChannel in Windows and OpenSSL or other PKI stacks in Linux should be able to figure out the right cert to use once it's available in the cert store). Perhaps this step should be included into the library code itself?

also, it would be interesting to test if this same behavior could be reprod on a previous version of .NET Core

**Comment by limeryls** [comment]
I have a similar problem.

When I use the not secured port (1883) all is working.

But once I want to communicate securely with my MQTT broker, the exchange of certificates between the broker and the client seems working good. For checking the exchange, I used a simple SslStream with the AuthenticateAsClient method, and it works with it.

However, by looking the trace logs, the MqttClient does not receive the "MqttConnAckPacket".


```batch
[2020-04-16T21:33:03.1320857Z] [1] [MqttClient] [Verbose]: Trying to connect with server 'broker:8883' (Timeout=00:00:10).
[2020-04-16T21:33:03.4522625Z] [7] [MqttClient] [Verbose]: Connection with server established.
[2020-04-16T21:33:03.4629036Z] [6] [MqttClient] [Verbose]: Start receiving packets.
[2020-04-16T21:33:03.5292792Z] [7] [MqttChannelAdapter] [Verbose]: TX (54 bytes) >>> Connect: [ClientId=Client2] [Username=XXXX] [Password=XXXX] [KeepAlivePeriod=15] [CleanSession=True]
[2020-04-16T21:33:06.4047882Z] [7] [MqttClient] [Verbose]: Disconnecting [Timeout=00:00:10]
[2020-04-16T21:33:06.4072681Z] [7] [MqttClient] [Verbose]: Disconnected from adapter.
[2020-04-16T21:33:06.4092282Z] [7] [MqttClient] [Info]: Disconnected.
[2020-04-16T21:33:06.4098719Z] [7] [MqttClient] [Verbose]: Stopped receiving packets.
### DISCONNECTED FROM SERVER ###
[2020-04-16T21:33:13.5392273Z] [6] [MqttClient] [Warning]: Timeout while waiting for packet of type 'MqttConnAckPacket'.
[2020-04-16T21:33:13.5415796Z] [6] [MqttClient] [Error]: Error while connecting with server.
MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.WaitOneAsync(TimeSpan timeout)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.AuthenticateAsync(IMqttChannelAdapter channelAdapter, MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
### CONNECTING FAILED ###
```

```csharp
IMqttFactory factory = new MqttFactory();
IMqttClient mqttClient = factory.CreateMqttClient();

MqttClientTlsOptions tlsOptions = new MqttClientTlsOptions
{
    UseTls = true,
    AllowUntrustedCertificates = true,
    IgnoreCertificateChainErrors = true,
    IgnoreCertificateRevocationErrors = true,
    SslProtocol = SslProtocols.Tls12
};

IMqttClientOptions options = new MqttClientOptionsBuilder()
    .WithClientId("Client2")
    .WithTcpServer(tcpOptions =>
    {
        tcpOptions.Server = "broker";
        tcpOptions.Port = 8883;
        tcpOptions.TlsOptions = tlsOptions;
    })
    .WithCredentials("XXXX", "XXXX")
    .WithCleanSession()
    .Build();
            
await mqttClient.ConnectAsync(options, CancellationToken.None);
```

**Comment by zhaopeiym** [comment]
It cannot solve the problem, under docker aspnet:3.0-alpine

Windows is fine, but Linux reports errors. `SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.`

**Comment by zhaopeiym** [comment]
> 在docker aspnet：3.0-alpine下无法解决问题
> 
> Windows很好，但是Linux报告错误。 `SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.`

已解决，两种方案实现TLS连接：
```
1、通过WebSocket 
var mqttClientOptions = new MqttClientOptionsBuilder()
             .WithClientId(clientID)
             .WithWebSocketServer("broker.hivemq.com:443/mqtt")
             .WithCredentials(userName, password)
             .WithTls();

2、只需要导入client.pfx，不需要ca.crt
var clientCert = new X509Certificate2(AppConfig.MqttPfxFile); 
var mqttClient = new MqttFactory().CreateManagedMqttClient();
var mqttClientOptions = new MqttClientOptionsBuilder()
             .WithClientId(clientID)
             .WithTcpServer(address, port)
             .WithCredentials(userName, password)
             .WithTls(new MqttClientOptionsBuilderTlsParameters()
             {
                 UseTls = true,
                 SslProtocol = System.Security.Authentication.SslProtocols.Tls12,
                 CertificateValidationHandler = (o) =>
                 {
                     return true;
                 },
                 Certificates = new []{                                      
                     clientCert,
                 }
             });
```
`生成pfx：openssl pkcs12 -export -in client.crt -inkey client.key -out client.pfx `

**Comment by janhumble** [comment]
I'm trying to replicate "self signed certificates in keystores" in MQTT.fx.  What would the TLS configuration look like to replicate the configuration below, ideally fully programmatically?

![Untitled](https://user-images.githubusercontent.com/19224631/120376754-3d35bd80-c2ea-11eb-80da-e335408bcc58.png)

**Comment by MrzJkl** [comment]
I still get this issue in .NET 6...

Adding CA Certificate and Client certificate to the Certstore does not fix it. 

Anyone else having this Problem?

**Comment by PWNTechIT** [comment]
> > 在docker aspnet：3.0-alpine下无法解决问题
> > Windows很好，但是Linux报告错误。 `SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.`
> 
> 已解决，两种方案实现TLS连接：
> 
> ```
> 1、通过WebSocket 
> var mqttClientOptions = new MqttClientOptionsBuilder()
>              .WithClientId(clientID)
>              .WithWebSocketServer("broker.hivemq.com:443/mqtt")
>              .WithCredentials(userName, password)
>              .WithTls();
> 
> 2、只需要导入client.pfx，不需要ca.crt
> var clientCert = new X509Certificate2(AppConfig.MqttPfxFile); 
> var mqttClient = new MqttFactory().CreateManagedMqttClient();
> var mqttClientOptions = new MqttClientOptionsBuilder()
>              .WithClientId(clientID)
>              .WithTcpServer(address, port)
>              .WithCredentials(userName, password)
>              .WithTls(new MqttClientOptionsBuilderTlsParameters()
>              {
>                  UseTls = true,
>                  SslProtocol = System.Security.Authentication.SslProtocols.Tls12,
>                  CertificateValidationHandler = (o) =>
>                  {
>                      return true;
>                  },
>                  Certificates = new []{                                      
>                      clientCert,
>                  }
>              });
> ```
> 
> `生成pfx：openssl pkcs12 -export -in client.crt -inkey client.key -out client.pfx `

Your solution works fine! Thanks for saving me another 2 hours of headaches!
