### ISSUE TITLE
MQTTNet hung during call to ManagedMQTTClient.Dispose()

### ISSUE THREAD

**Issue by kwende** [chkr1011/MQTTnet#765]
### Describe the bug
During a network outage, we experienced a hang in the Dispose call of the ManagedMQTTClient at [this location in the code](https://github.com/chkr1011/MQTTnet/blob/2918be18c6c6529584cd1d78e09ebb3fc0819e4f/Source/MQTTnet.Extensions.ManagedClient/ManagedMqttClient.cs#L251). It's unclear precisely what happened to cause this situation other than the environmental situation which I just described: a network outage. 

### Which project is your bug related to?
- ManagedClient

### To Reproduce
1. Using this version of MQTTnet v4.0.30319.
2. Run [this](https://github.com/chkr1011/MQTTnet/blob/2918be18c6c6529584cd1d78e09ebb3fc0819e4f/Source/MQTTnet.Extensions.ManagedClient/ManagedMqttClient.cs#L251) code.
3. With these arguments: None.
4. See a hang if the _maintainConnectionTask never completes.

### Expected behavior
I expect the code to eventually timeout and/or toss a timeout exception as opposed to hanging indefinitely. Our software will restart the box if we notice something (like a bad network) has happened, but we also expected the underlying software to not hang during shutdown. This resulted in our product not successfully restarting the box and manual resets being required. 

We could trap a timeout exception and handle it the best we can during shutdown, but we cannot hang indefinitely. 

### Screenshots
![image](https://user-images.githubusercontent.com/526471/66070356-c5146480-e516-11e9-915b-38f0d0c17621.png)
.

### Additional context / logging
NA

### Code example
NA

**Comment by JanEggers** [comment]
maybe we need to pull in Microsoft.Bcl.AsyncInterfaces and make the ManagedClient AsyncDisposable?

**Comment by kwende** [comment]
I have motivation for this fix. Would you want me to try making this change and doing a PR?

**Comment by chkr1011** [comment]
Isn't it enough to use a SpinWait instead of Task.WaitAny? Or we can get rid of the wait at all. Why do we care if this task has completed first? The task implementation has proper exception handling and should exit without any issues. 🤔

**Comment by ummarbhutta** [comment]
We are facing similar issue with `ManagedMQTTClient.StopAsync` and it stuck forever. I am using version `3.0.13`

**Comment by chkr1011** [comment]
Please try again with RC8. I added a timeout where the DISCONNECT packet is sent (which fails due to network issues).

**Comment by ummarbhutta** [comment]
Hi @chkr1011 ,
Thanks I tried RC8 and it is giving following error

 ```
System.ComponentModel.Win32Exception (0x80090331): The client and server cannot communicate, because they do not possess a common algorithm.
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
```

Any idea, I am using [https://www.emqx.io/products/broker](emqx broker) version `3.2.3` with self signed certificate over TLS. It doesn't show this issue with older version or `3.0.13`

**Comment by aliaslam63** [comment]
Hi @chkr1011,
Any update on the above exception?

**Comment by KMZeiseBTAC** [comment]
It looks like your are using the library from none async code. Some of the tasks of the library are scheduled on the thread you create it on, so they will not run. Especially the completion task will not stop because it cannot be scheduled, so it will deadlock. If you change your code to use async functions, the problem will go away.

**Comment by chkr1011** [comment]
@ummarbhutta The exception is thrown because client and server do not share a common encryption algorithm. The detection was changed in later versions so that the OS will now decide which can be used. Some OS no longer allow TLS1.2 and lower. To you have to explicitly set to 1.2 in order to get rid of the exception.

**Comment by ddobric** [comment]
Just as additional info. It might be helpful to fix the issue.
Following code blocks inside *Dispose*.

`
            CancellationTokenSource tSrc = new CancellationTokenSource();

            Console.CancelKeyPress += (obj, arg) =>
            {
                Console.WriteLine("Cancel detected.");
                tSrc.Cancel();
            }; 

            var mqttFactory = new MqttFactory();

            using (var mqttClient = new MqttFactory().CreateManagedMqttClient())
            {
                var options = new ManagedMqttClientOptionsBuilder()
                .WithAutoReconnectDelay(TimeSpan.FromSeconds(30))
                .WithClientOptions(new MqttClientOptionsBuilder()
                   . . .
                    .WithCleanSession()
                    .Build())
                .Build();

                mqttClient.ConnectedAsync += (args) =>
                {
                    _ = Task.Run(async () =>
                    {
                        while (true)
                        {
                            string? userTxt = "xy";

                            var applicationMessage = new MqttApplicationMessageBuilder()
                            .WithTopic("samples/topic")
                            .WithPayload(userTxt)
                            .Build();

                            await mqttClient.EnqueueAsync(new ManagedMqttApplicationMessage()
                            {
                                Id = Guid.NewGuid(),
                                ApplicationMessage = applicationMessage
                            });
                        }
                    });

                    return Task.CompletedTask;
                };

                await mqttClient.StartAsync(options);

                 tSrc.Token.WaitHandle.WaitOne();

                Console.WriteLine("...");

                // Dispose hangs!! Not required here. Used only to show hanging.
                mqttClient.Dispose();
            }// Without using explicit invoke to Dispose(), the code will block here.

            Console.WriteLine("Exiting application.");                
        }`

**Comment by cxtal** [comment]
Confirming the problem with the managed client in particular the fact that ```await _mqttClient.StopAsync(true);``` hangs forever. 

The MQTTnet managed client connects to a standard Eclipse-Mosquitto broker with no special configuration aside the default listening endpoint and port.

Additionally, it would be advisable to be able to pass a cancellation token to the ```StopAsync``` - as long as methods are async, they should all be able to be bound by a cancellation token, even if the operations that they perform are not expected to be long. At worst, when cancelling ```StopAsync```, an exception should be thrown but is better to just forcibly disconnect the client equivalently to ```StopAsync(false)``` in case cancellation is requested. Async methods without any way to be cancelled can and will stall forever if something goes wrong. When performing long operations like loops, it is also advisable to check whether ```cancellationToken.IsCancellationRequested``` upon each iteration even if the methods within the loop body do not even contain asynchronous methods such that the iteration itself can be cancelled (mentioning because I did not look up what ```StopAsync``` does within its body).

A signature like:
 ```
await _mqttClient.StopAsync(true, _cancellationToken);
```
would be ideal.
