### ISSUE TITLE
 .NET Core 3.0 .AddressInUseException: Address already in use 

### ISSUE THREAD

**Issue by AndMu** [chkr1011/MQTTnet#809]
Looks that AddMqttTcpServerAdapter and AddMqttWebSocketServerAdapter open same port twice. that works on Windows and Ubuntu, but on Docker it crashes on start with AddressInUseException: Address already in use exception.

netstat clearly shows that port is opened twice:
![image](https://user-images.githubusercontent.com/1674086/69765127-9effef00-116a-11ea-90c8-b54fb870c59c.png)

If I remove AddMqttTcpServerAdapter or AddMqttWebSocketServerAdapter, it starts fine on Docker.

Code:
```
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseKestrel(o => {
            o.ListenAnyIP(1885, l => l.UseMqtt()); // mqtt pipeline
            o.ListenAnyIP(5000); // default http pipeline
        })
        .Build();

private void ConfigureMqttServices(IServiceCollection services)
{
    //this adds a hosted mqtt server to the services
    services.AddHostedMqttServer(
        builder =>
        {
            builder.WithDefaultEndpointPort(1885);
        });

    //this adds tcp server support based on System.Net.Socket
    services.AddMqttTcpServerAdapter();

    //this adds websocket support
    services.AddMqttWebSocketServerAdapter();
}
```

Exception 
```
2019-11-28 11:13:39.8815 FATAL [1] [Microsoft.AspNetCore.Server.Kestrel] Unable to start Kestrel. System.IO.IOException: Failed to bind to address http://[::]:1885: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
```

**Comment by SeppPenner** [comment]
Just for reference / information. This is **ASP.Net**. In simple NetCore it works e.g. like in my project: https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfigHashedPasswords/blob/master/NetCoreMQTTExampleJsonConfigHashedPasswords/Program.cs

**Comment by AndMu** [comment]
Updated description, looks like it is not related to core 3.0

**Comment by AndMu** [comment]
Ok I think I figured out. Examples on wiki are misleading.
To use just websockets it should be:
```
.UseKestrel(o => {
                    o.ListenAnyIP(5000); // default http pipeline
                })
private void ConfigureMqttServices(IServiceCollection services)
        {
            services.AddHostedMqttServer(
                        builder =>
                        {
                            builder.WithoutDefaultEndpoint();
                        })
                    .AddMqttConnectionHandler()
                    .AddConnections();
        }
  app.UseEndpoints(c => c.MapConnectionHandler<MqttConnectionHandler>("/mqtt",
                                                                                options =>
                                                                                {
                                                                                    options.WebSockets.SubProtocolSelector = MQTTnet.AspNetCore.ApplicationBuilderExtensions.SelectSubProtocol;
                                                                                }));
```

To use both WebSockets and TCP you simply add
```
 services.AddMqttTcpServerAdapter();
and 
o.ListenAnyIP(1883, l => l.UseMqtt()); // mqtt pipeline
```

**Comment by SeppPenner** [comment]
@AndMu What would you change in the documentation: https://github.com/chkr1011/MQTTnet/wiki/Server#aspnet-core-21?
