### ISSUE TITLE
Load Balancing With Shared Subscriptions - MQTT Client

### ISSUE THREAD

**Issue by vitaly-trevidi** [chkr1011/MQTTnet#821]
Dear Developers and founders of MQTTnet project!

First of all, let me express my personal apprisiation to you guys! This project has an extreamly high impact on our dependent projects we workin on. This one is the one of best toys we ever used in our Message Queueing world. Extreamly relieble, easy to use, and easy to embed!  

Everything is perfect but one of the fetures of MQTT v5 would be great to have at the Client/ManagedClient supported by Server. 

The fearure we really need is called - Load Balancing With Shared Subscriptions intoduced by The HiveMQ Team. 
https://www.hivemq.com/blog/mqtt-client-load-balancing-with-shared-subscriptions/

We can cover some functionaly of this by dedicated Client Subscriptions and publishing to dedicated Topics, or use Application Message Interseptor on Server side, but those methods are not very ellegant and eating some extra machine resources. 

In our projects we have a requirement to implement multy-threded Client. 10 objects Subscribe to single shared topic. Expected behavior just like JMS Queue, which delivers the  first message in the queue to just one session, the second message in the queue to the most Idle session and so on (load balanser).

**Comment by chkr1011** [comment]
Hi, thank you for your feedback. At the moment we have no time left to implement more MQTTv5 features. But I assume this will change in a couple of months. If you have some experience with this please consider making an proposal via pull request.
Best regards
Christian

**Comment by rquackenbush** [comment]
Would like to add my voice to this... Both for this being a great library and for the load balancing with shared subscriptions for this feature. I don't feel I understand MQTT 5 quite well enough to contribute a pull request at this time, but that might change.

**Comment by rdinogit** [comment]
I would also like to show my interest towards this feature. And I also feel like I do not yet have enough knowledge to be able to contribute with a pull request. Congratulations for the amazing library!

**Comment by redradist** [comment]
Guys, is this topic relate to load balancing with MQTT ? Seems like this is Load Balancing with additional feature like shared subscription ...
I have created topic https://github.com/chkr1011/MQTTnet/issues/983 related how to create Load Balancing with MQTTnet ... in documentation I have not found any useful information ... is there solution for this issue ?

**Comment by SeppPenner** [comment]
I have tried to do something like this, but it's not yet finished: https://github.com/SeppPenner/NetCoreMQTTExampleCluster

**Comment by chkr1011** [comment]
Shared subscriptions are working fine when using the client only. The feature is not (yet) implemented for the server.

**Comment by kanilZ** [comment]
@chkr1011 Excuse me but whether it would work with ManagedMqttClient? And is any example of how to use it?

**Comment by rshillington** [comment]
I have confirmed this does work with the ManagedMqttClient (using HiveMQ as the broker)

**Comment by PanagiotisVag1991** [comment]
@chkr1011 Shared Subscriptions does not work on client. When I publish a message to a shared topic, application returns 

`Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unexpected DISCONNECT (Reason code=ProtocolError) received.
MQTTnet.Client.MqttClientUnexpectedDisconnectReceivedException: Unexpected DISCONNECT (Reason code=ProtocolError) received.
   at MQTTnet.PacketDispatcher.MqttPacketAwaitable`1.<WaitOneAsync>d__6[[MQTTnet.Packets.MqttPubAckPacket, MQTTnet, Version=4.3.3.952, Culture=neutral, PublicKeyToken=fdb7629f2e364a63]].MoveNext()
   at MQTTnet.Client.MqttClient.<Request>d__70`1[[MQTTnet.Packets.MqttPubAckPacket, MQTTnet, Version=4.3.3.952, Culture=neutral, PublicKeyToken=fdb7629f2e364a63]].MoveNext()
   at MQTTnet.Client.MqttClient.PublishAtLeastOnce(MqttPublishPacket publishPacket, CancellationToken cancellationToken)
   at PhotoChallenges.AdminPanel.Website.Wasm.Services.MQTT.MQTTService.PublishMessageAsync(MqttApplicationMessage message, CancellationToken cancellationToken) in F:\Workspaces\Photo-Challenges\Websites\PC-AdminPanel-Website\Services\MQTT\MQTTService.cs:line 221
   at PhotoChallenges.AdminPanel.Website.Wasm.Pages.Login.LoginAsycn() in F:\Workspaces\Photo-Challenges\Websites\PC-AdminPanel-Website\Pages\Login.razor:line 245
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)`

Can we have any information about when this feature will be add.

**Comment by kanilsz** [comment]
Should this issue be closed? Because such a feature has already implemented.
