### ISSUE TITLE
Bug: ClientMessageQueueInterceptor breaks the broker due to QoS levels

### ISSUE THREAD

**Issue by msallin** [chkr1011/MQTTnet#978]
### Describe the bug
If a Client A subscribes a topic with QoS 0 and a client B publishes with QoS 1 AND a `ClientMessageQueueInterceptor` is used, the broker throws an exception.

### Which project is your bug related to?
- Server

### To Reproduce
1. Using this version of MQTTnet '3.0.12'.
2. Add a `ClientMessageQueueInterceptor`.
3. Subscribe with a Client to a topic "A" and QoS 0
4. Publish with a Client to topic "A" and QoS 1
5. Exception is thrown (`MqttCommunicationException`)

### Expected behavior
The usage of a `ClientMessageQueueInterceptor` should work correctly.

### Additional context / logging
The following lines lead to the exception:
- QoS is set to the `publishPacket` correctly from `queuedApplicationMessage.QualityOfServiceLevel`  (i.e. QoS from the subscription) https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientConnection.cs#L395
- The `MqttClientMessageQueueInterceptorContext` is created and passed to the handler. The information  `queuedApplicationMessage.QualityOfServiceLevel` isn't available on the context.
https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientConnection.cs#L407
- The `publishPacket.QualityOfServiceLevel ` is set again BUT from `ApplicationMessage.QualityOfServiceLevel` which overwrites the correct one from `queuedApplicationMessage.QualityOfServiceLevel` (i.e. with the QoS from the published message)
https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientConnection.cs#L424:

The thrown exceptions:

Message was published with QoS 1 but client subscribed with QoS 0:
```
MQTT Trace: Sending publish packet failed: Communication exception (ClientId: xy).
MQTTnet.Exceptions.MqttCommunicationException: Packet identifier must be empty if QoS == 0 [MQTT-2.3.1-5]. ---> MQTTnet.Exceptions.MqttProtocolViolationException: Packet identifier must be empty if QoS == 0 [MQTT-2.3.1-5].
   at MQTTnet.Formatter.V3.MqttV310PacketFormatter.EncodePublishPacket(MqttPublishPacket packet, IMqttPacketWriter packetWriter)
   at MQTTnet.Formatter.V3.MqttV310PacketFormatter.Encode(MqttBasePacket packet)
   at MQTTnet.Adapter.MqttChannelAdapter.<SendPacketAsync>d__33.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.<SendPacketAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Server.MqttClientConnection.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Server.MqttClientConnection.<SendPendingPacketsAsync>d__45.MoveNext()
```

Message was published with QoS 0 but client subscribed with QoS 1:
```
MQTT Trace: Sending publish packet failed: Communication exception (ClientId: xy).
MQTTnet.Exceptions.MqttCommunicationException: Publish packet has no packet identifier. ---> MQTTnet.Exceptions.MqttProtocolViolationException: Publish packet has no packet identifier.
   at MQTTnet.Formatter.V3.MqttV310PacketFormatter.EncodePublishPacket(MqttPublishPacket packet, IMqttPacketWriter packetWriter)
   at MQTTnet.Formatter.V3.MqttV310PacketFormatter.Encode(MqttBasePacket packet)
   at MQTTnet.Adapter.MqttChannelAdapter.<SendPacketAsync>d__33.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.<SendPacketAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Server.MqttClientConnection.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Server.MqttClientConnection.<SendPendingPacketsAsync>d__45.MoveNext()
```

### Discussion
This is a bug which is very urgent for us and we would like to submit a Pull Request. We see the following possibilities:
1. Don't allow the interceptor to change the QoS level at all (means, just delete the line)
2. Pass and the correct QoS level (means, if the interceptor doesn't change something, the correct level as before is set)

**Comment by chkr1011** [comment]
@msallin Please create a pull request for that. To me option 2 is the better choice.

**Comment by msallin** [comment]
Thank you for your quick reaction!

I create the PR. I tried to get as close as possible to the current coding style and wrote tests for my adjustments. I hope this helps to fast merge the PR and release the bugfix in timely fashion...

Let me know in the PR when there is something further to do.

**Comment by msallin** [comment]
The PR is now merged. 
When can we expect a release which contains this bugfix?

**Comment by chkr1011** [comment]
@msallin I have no plans yet for a new release but I will release an RC soon so you can already make use of the latest changes.

**Comment by msallin** [comment]
Sounds good. Ty! I will close the issue as soon as the RC is released.

**Comment by msallin** [comment]
Would be great to know when you are able to release an RC, can you provide a timeline?
We would like to plan when we are able to abdone our fork as well as workarounds and use the NuGet again.
Let me know if I can assist you somehow.

**Comment by msallin** [comment]
https://github.com/chkr1011/MQTTnet/releases/tag/v3.0.13
