### ISSUE TITLE
Possbile concurrent issue between `ManagedMqttClient.ReconnectIfRequiredAsync()` and `MqttClient.DisconnectInternalAsync()`?

### ISSUE THREAD

**Issue by yyjdelete** [chkr1011/MQTTnet#996]
### Describe the bug
Failed to make an reproduce, but I get an MqttClient with `{ IsDisposed=false, _isConnected=true, _backgroundCancellationTokenSource=null,_isDisconnectPending=0, _publishPacketReceiverQueue=null, _keepAlivePacketsSenderTask=canceled, _packetReceiverTask =RanToCompletion, _publishPacketReceiverTask=canceled}` with ManagedMqttClient, and reconnect not work in this state.

Is it possbile concurrent issue between ManagedMqttClient.ReconnectIfRequiredAsync() and `MqttClient.DisconnectInternalAsync()`, if `ReconnectIfRequiredAsync()` is called while `DisconnectInternalAsync()` is still running(IsConnected is already false), and get an MqttClient in conflict state?

### Which project is your bug related to?
- Client : 3.0.12
- ManagedClient : 3.0.12

### To Reproduce
Failed to make an reproduce.

### Expected behavior
Auto reconnected should be handle by ManagedMqttClient after network issue.

**Comment by yyjdelete** [comment]
Reconnect may random frozen due to broken state in MqttClient.

```cs
using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Client.Connecting;
using MQTTnet.Client.Options;
using MQTTnet.Extensions.ManagedClient;
using MQTTnet.Server;
using System;
using System.Threading.Tasks;

namespace ConsoleApp2
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var factory = new MqttFactory();
            //var srv = factory.CreateMqttServer()
            //    srv.StartAsync(
            //        new MqttServerOptionsBuilder()
            //        .WithDefaultEndpointPort(1883)
            //        .Build());
            var cli0 = (MqttClient)factory.CreateMqttClient();
            var cli = new ManagedMqttClient(cli0, factory.DefaultLogger);
            int i = 0;
            cli.ConnectedHandler = new MqttClientConnectedHandlerDelegate(e =>
            {
                var idx = i++;
                Console.WriteLine("Connected " + idx);
                Func<Task> a = async () =>
                {
                    await cli0.DisconnectAsync();
                    Console.WriteLine("Disconnected " + idx);
                };
                _ = a.Invoke();
            });
            await cli.StartAsync(new ManagedMqttClientOptionsBuilder()
                        .WithAutoReconnect()
                        .WithAutoReconnectDelay(TimeSpan.FromMilliseconds(10))
                        .WithClientOptions(new MqttClientOptionsBuilder()
                            .WithKeepAlivePeriod(TimeSpan.FromSeconds(5))
                            .WithTcpServer("127.0.0.1", 1883))
                        .Build());

            for (var z = 0; z < 65535; ++z)
            {
                _ = cli.PublishAsync("a", "b");
            }
            while (true)
            {
                Console.ReadLine();
                Console.WriteLine($"pending={cli.PendingApplicationMessagesCount}, IsConnected={cli.IsConnected}, " +
                    $"_backgroundCancellationTokenSource={typeof(MqttClient).GetField("_backgroundCancellationTokenSource", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(cli0)}, " +
                    $"_publishPacketReceiverQueue={typeof(MqttClient).GetField("_publishPacketReceiverQueue", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(cli0)}, " +
                    $"_publishPacketReceiverTask={((Task)typeof(MqttClient).GetField("_publishPacketReceiverTask", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(cli0))?.Status}, " +
                    $"_packetReceiverTask={((Task)typeof(MqttClient).GetField("_packetReceiverTask", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(cli0))?.Status}, " +
                    $"_keepAlivePacketsSenderTask={((Task)typeof(MqttClient).GetField("_keepAlivePacketsSenderTask", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(cli0))?.Status}" +
                    "");
            }
        }
    }
}
```

**Comment by redradist** [comment]
Seems like this issue relate to https://github.com/chkr1011/MQTTnet/issues/966

@yyjdelete I have the same issue with ManagedClient in case when MqttBroker is down ... All Xamarin application hangs up ...

Seems like it use too many threads ...
```console
"Thread Pool Worker"
"Thread Pool Worker"09-29 01:00:17.671 I/system_server( 1285): libdebuggerd_client: started dumping process 11552
09-29 01:00:17.671 D/AppEyeBinderBlock( 1285): read binder transaction begin
09-29 01:00:17.671 I/system_server( 1285): libdebuggerd_client: started dumping process 11552
09-29 01:00:17.672 I//system/bin/tombstoned(  763): registered intercept for pid 11552 and type kDebuggerdJavaBacktrace
09-29 01:00:17.675 E/mono    (11552): Full thread dump:

"Timer-Scheduler"  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Threading.WaitHandle.Wait_internal (intptr*,int,bool,int) <0x00007>
  at System.Threading.WaitHandle.WaitOneNative (System.Runtime.InteropServices.SafeHandle,uint,bool,bool) [0x00019] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Threading/WaitHandle.cs:90
  at System.Threading.WaitHandle.InternalWaitOne (System.Runtime.InteropServices.SafeHandle,long,bool,bool) [0x00014] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/waithandle.cs:259
  at System.Threading.WaitHandle.WaitOne (long,bool) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/waithandle.cs:248
  at System.Threading.WaitHandle.WaitOne (int,bool) [0x00019] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/waithandle.cs:215
  at System.Threading.WaitHandle.WaitOne (int) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/waithandle.cs:236
  at System.Threading.Timer/Scheduler.SchedulerThread () [0x0003c] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Threading/Timer.cs:293
  at System.Threading.ThreadHelper.ThreadStart_Context (object) [0x00014] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/thread.cs:74
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00071] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:968
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:910
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) [0x0002b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:899
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/threading/thread.cs:111
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x00067] in <0381c8f952fb47759ee29160e807b17d>:0

"Thread Pool Worker"
"Thread Pool Worker"
"<threadpool thread>"
"Thread Pool I/O Selector"09-29 01:00:17.687 I/TrafficMonitor( 1285): expired arrive. level:-1
09-29 01:00:17.688 I/TrafficMonitor( 1285): update:rxPkts:2,txPkts:0,rxBytes:402,txBytes:0
09-29 01:00:17.689 I/TrafficMonitor( 1285): start expired. level:-1
09-29 01:00:17.689 I/TrafficMonitor( 1285): gettimer:interval=5000
09-29 01:00:17.689 I/TrafficMonitor( 1285): during_ms:5002,period_ms:2000
09-29 01:00:17.689 I/TrafficMonitor( 1285): count:523,rx_sum:2,tx_sum:0,rxBytes:402,during_ms:5002,rx_speed:80.36785285885647,tx_speed:0.0,rto:0.0

"<unnamed thread>"  at <unknown> <0xffffffff>
  at System.Collections.Generic.List`1<Xamarin.Forms.WeakEventManager/Subscription>.EnsureCapacity (int) [0x00036] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:426
  at System.Collections.Generic.List`1<Xamarin.Forms.WeakEventManager/Subscription>.AddWithResize (Xamarin.Forms.WeakEventManager/Subscription) [0x00007] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:231
  at System.Collections.Generic.List`1<Xamarin.Forms.WeakEventManager/Subscription>.Add (Xamarin.Forms.WeakEventManager/Subscription) [0x00034] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:222
  at Xamarin.Forms.WeakEventManager.AddEventHandler (string,object,System.Reflection.MethodInfo) [0x00034] in D:\a\1\s\Xamarin.Forms.Core\WeakEventManager.cs:116
  at Xamarin.Forms.WeakEventManager.AddEventHandler (System.EventHandler,string) [0x00021] in D:\a\1\s\Xamarin.Forms.Core\WeakEventManager.cs:34
  at Xamarin.Forms.ImageSource.add_SourceChanged (System.EventHandler) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\ImageSource.cs:150
  at Xamarin.Forms.ImageElement.OnImageSourceChanged (Xamarin.Forms.BindableObject,object,object) [0x00014] in D:\a\1\s\Xamarin.Forms.Core\ImageElement.cs:25
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty,Xamarin.Forms.BindableObject/BindablePropertyContext,object,bool,Xamarin.Forms.Internals.SetValueFlags,bool) [0x00120] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:463
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty,object,Xamarin.Forms.Internals.SetValueFlags,Xamarin.Forms.BindableObject/SetValuePrivateFlags) [0x00173] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:397
  at Xamarin.Forms.BindingExpression.ApplyCore (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty,bool) [0x00214] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:155
  at Xamarin.Forms.BindingExpression.Apply (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty) [0x0006b] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:72
  at Xamarin.Forms.Binding.Apply (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty,bool) [0x0006d] in D:\a\1\s\Xamarin.Forms.Core\Binding.cs:138
  at Xamarin.Forms.BindableObject.ApplyBindings (bool,bool) [0x00041] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:480
  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject,object) [0x0005a] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:209
  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:475
  at Xamarin.Forms.Element.<OnBindingContextChanged>b__82_0 (Xamarin.Forms.BindableObject,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:306
  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext<T_REF> (Xamarin.Forms.BindableObject,System.Collections.Generic.IList`1<T_REF>,System.Action`2<Xamarin.Forms.BindableObject, object>) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\BindableObjectExtensions.cs:28
  at Xamarin.Forms.Element.OnBindingContextChanged () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:304
  at Xamarin.Forms.VisualElement.OnBindingContextChanged () [0x00006] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:769
  at Xamarin.Forms.View.OnBindingContextChanged () [0x0000c] in D:\a\1\s\Xamarin.Forms.Core\View.cs:158
  at Xamarin.Forms.Grid.OnBindingContextChanged () [0x00006] in D:\a\1\s\Xamarin.Forms.Core\Grid.cs:149
  at Xamarin.Forms.BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject,object,object) [0x0000f] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:500
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty,Xamarin.Forms.BindableObject/BindablePropertyContext,object,bool,Xamarin.Forms.Internals.SetValueFlags,bool) [0x00120] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:463
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty,object,Xamarin.Forms.Internals.SetValueFlags,Xamarin.Forms.BindableObject/SetValuePrivateFlags) [0x00173] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:397
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty,object,bool,bool) [0x00042] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:334
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty,object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:311
  at Xamarin.Forms.BindableObject.set_BindingContext (object) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:41
  at Xamarin.Forms.Platform.Android.ShellFlyoutRecyclerAdapter/ElementViewHolder.set_Element (Xamarin.Forms.Element) [0x0004d] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellFlyoutRecyclerAdapter.cs:272
  at Xamarin.Forms.Platform.Android.ShellFlyoutRecyclerAdapter.OnBindViewHolder (Android.Support.V7.Widget.RecyclerView/ViewHolder,int) [0x0002a] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellFlyoutRecyclerAdapter.cs:77
  at Android.Support.V7.Widget.RecyclerView/Adapter.n_OnBindViewHolder_Landroid_support_v7_widget_RecyclerView_ViewHolder_I (intptr,intptr,intptr,int) [0x00012] in <844c913cb32f4510879031be59eb1dce>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.63 (intptr,intptr,intptr,int) [0x0001d] in <0623d8432cef4751a77985c521d75c2f>:0
  at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.63 (intptr,intptr,intptr,int) [0x00035] in <0623d8432cef4751a77985c521d75c2f>:0
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,intptr) <0x00007>
  at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00079] in <3ffd030629264cf9a5adda85ea742eb9>:0
  at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeNonvirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x00021] in <3ffd030629264cf9a5adda85ea742eb9>:0
  at Android.Views.ViewGroup.Layout (int,int,int,int) [0x00069] in <0623d8432cef4751a77985c521d75c2f>:0
  at Xamarin.Forms.Platform.Android.ShellRenderer.OnElementSizeChanged (object,System.EventArgs) [0x00092] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellRenderer.cs:315
  at Xamarin.Forms.VisualElement.SetSize (double,double) [0x00029] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:1047
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle) [0x0005d] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:357
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:724
  at Xamarin.Forms.Platform.Android.AppCompat.Platform.LayoutRootPage (Xamarin.Forms.Page,int,int) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:405
  at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.Platform.Android.IPlatformLayout.OnLayout (bool,int,int,int,int) [0x0000c] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:232
  at Xamarin.Forms.Platform.Android.PlatformRenderer.OnLayout (bool,int,int,int,int) [0x0001a] in D:\a\1\s\Xamarin.Forms.Platform.Android\PlatformRenderer.cs:75
  at Android.Views.ViewGroup.n_OnLayout_ZIIII (intptr,intptr,bool,int,int,int,int) [0x00010] in <0623d8432cef4751a77985c521d75c2f>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.38 (intptr,intptr,bool,int,int,int,int) [0x0002f] in <0623d8432cef4751a77985c521d75c2f>:0
  at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.38 (intptr,intptr,int,int,int,int,int) [0x00045] in <0623d8432cef4751a77985c521d75c2f>:0

"Thread Pool Worker"
"Thread Pool Worker"  at <unknown> <0xffffffff>
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x00007>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x0002b] in <0381c8f952fb47759ee29160e807b17d>:0

"Finalizer"
"Thread Pool Worker"
"Debugger agent"
"Thread Pool Worker"
"Thread Pool Worker"  at <unknown> <0xffffffff>
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x00007>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x0002b] in <0381c8f952fb47759ee29160e807b17d>:0

"<threadpool thread>"
"Thread Pool Worker"09-29 01:00:17.888 D/AppEyeBinderBlock( 1285): read binder transaction end
```

**Comment by redradist** [comment]
@yyjdelete I have figured out that hanging up come in Debug mode for Xamarin application, seems like debugger use some thread that with addition with failed connection to broker hanging up

When I run application without debug mode, just tap on icon, it starts properly ...

Also when I add _managedMqttClient.ConnectingFailedHandler than even in Debug mode application works properly after connection is failed ...

**Comment by chkr1011** [comment]
@redradist Do you mean that adding the _ConnectingFailedHandler_ fixes the issue also in _Debug_ mode?

**Comment by yyjdelete** [comment]
@redradist @yyjdelete 
They should be different issue, this one is reproducable with Release build and without debugger attached.

**Comment by redradist** [comment]
@chkr1011 @yyjdelete My issue was not related to library, it was due to bug in Rider IDE ;)

**Comment by yyjdelete** [comment]
Also reported as #1010, the message looks similar
```
[2021-02-22T01:53:32.5838992Z] [] [1] [ManagedMqttClient] [Info]: Started
[2021-02-22T01:53:32.6006971Z] [] [4] [MqttClient] [Verbose]: Trying to connect with server '127.0.0.1:1883' (Timeout=00:00:10).
[2021-02-22T01:53:32.6660187Z] [] [6] [MqttClient] [Verbose]: Connection with server established.
[2021-02-22T01:53:32.6829460Z] [] [6] [MqttChannelAdapter] [Verbose]: TX (46 bytes) >>> Connect: [ClientId=1c21a5788f96425e979da6464053cea8] [Username=] [Password=] [KeepAlivePeriod=5] [CleanSession=True]
[2021-02-22T01:53:32.7053783Z] [] [4] [MqttClient] [Verbose]: Start receiving packets.
[2021-02-22T01:53:32.7167918Z] [] [4] [MqttChannelAdapter] [Verbose]: RX (4 bytes) <<< ConnAck: [ReturnCode=ConnectionAccepted] [ReasonCode=] [IsSessionPresent=False]
[2021-02-22T01:53:32.7240168Z] [] [8] [MqttClient] [Verbose]: Authenticated MQTT connection with server established.
[2021-02-22T01:53:32.7242224Z] [] [8] [MqttClient] [Info]: Connected.
Connected 0
[2021-02-22T01:53:32.7275712Z] [] [4] [MqttClient] [Verbose]: Start sending keep alive packets.
[2021-02-22T01:53:32.7277774Z] [] [8] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> Disconnect: [ReasonCode=]
[2021-02-22T01:53:32.7290599Z] [] [6] [MqttClient] [Verbose]: Stopped receiving packets.
[2021-02-22T01:53:32.7342185Z] [] [8] [MqttClient] [Verbose]: Stopped sending keep alive packets.
[2021-02-22T01:53:32.7343681Z] [] [8] [MqttClient] [Verbose]: Disconnecting [Timeout=00:00:10]
[2021-02-22T01:53:32.7359609Z] [] [8] [MqttClient] [Verbose]: Disconnected from adapter.
[2021-02-22T01:53:32.7403504Z] [] [8] [ManagedMqttClient] [Info]: Publishing subscriptions at reconnect
[2021-02-22T01:53:32.7414926Z] [] [8] [MqttClient] [Verbose]: Trying to connect with server '127.0.0.1:1883' (Timeout=00:00:10).
[2021-02-22T01:53:32.7420068Z] [] [6] [MqttClient] [Verbose]: Connection with server established.
[2021-02-22T01:53:32.7421615Z] [] [6] [MqttChannelAdapter] [Verbose]: TX (46 bytes) >>> Connect: [ClientId=1c21a5788f96425e979da6464053cea8] [Username=] [Password=] [KeepAlivePeriod=5] [CleanSession=True]
[2021-02-22T01:53:32.7423106Z] [] [9] [MqttClient] [Verbose]: Start receiving packets.
[2021-02-22T01:53:32.7424493Z] [] [9] [MqttChannelAdapter] [Verbose]: RX (4 bytes) <<< ConnAck: [ReturnCode=ConnectionAccepted] [ReasonCode=] [IsSessionPresent=False]
[2021-02-22T01:53:32.7425706Z] [] [9] [MqttClient] [Verbose]: Authenticated MQTT connection with server established.
[2021-02-22T01:53:32.7426287Z] [] [9] [MqttClient] [Info]: Connected.
[2021-02-22T01:53:32.7426480Z] [] [8] [MqttClient] [Verbose]: Start sending keep alive packets.
Connected 1
[2021-02-22T01:53:32.7432699Z] [] [6] [MqttClient] [Verbose]: Stopped receiving packets.
[2021-02-22T01:53:32.7433018Z] [] [9] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> Disconnect: [ReasonCode=]
[2021-02-22T01:53:32.7433740Z] [] [5] [ManagedMqttClient] [Verbose]: Stopped publishing messages.
[2021-02-22T01:53:32.7437497Z] [] [9] [MqttClient] [Verbose]: Stopped sending keep alive packets.
[2021-02-22T01:53:32.7441246Z] [] [9] [MqttClient] [Verbose]: Disconnecting [Timeout=00:00:10]
[2021-02-22T01:53:32.7445914Z] [] [9] [MqttClient] [Verbose]: Disconnected from adapter.
[2021-02-22T01:53:32.7447660Z] [] [9] [ManagedMqttClient] [Info]: Publishing subscriptions at reconnect
[2021-02-22T01:53:32.7450658Z] [] [8] [ManagedMqttClient] [Verbose]: Stopped publishing messages.
[2021-02-22T01:53:32.7450779Z] [] [9] [MqttClient] [Verbose]: Trying to connect with server '127.0.0.1:1883' (Timeout=00:00:10).
[2021-02-22T01:53:32.7456294Z] [] [6] [MqttClient] [Verbose]: Connection with server established.
[2021-02-22T01:53:32.7457309Z] [] [6] [MqttChannelAdapter] [Verbose]: TX (46 bytes) >>> Connect: [ClientId=1c21a5788f96425e979da6464053cea8] [Username=] [Password=] [KeepAlivePeriod=5] [CleanSession=True]
[2021-02-22T01:53:32.7461191Z] [] [9] [MqttClient] [Verbose]: Start receiving packets.
[2021-02-22T01:53:32.7490117Z] [] [4] [MqttClient] [Info]: Disconnected.
[2021-02-22T01:53:32.7490709Z] [] [5] [MqttClient] [Info]: Disconnected.
[2021-02-22T01:53:32.7492111Z] [] [9] [MqttClient] [Verbose]: Stopped receiving packets.
Disconnected 0
Disconnected 1
[2021-02-22T01:53:42.7498817Z] [] [4] [MqttClient] [Warning]: Timeout while waiting for response packet (MqttConnAckPacket).
[2021-02-22T01:53:42.7502637Z] [] [4] [MqttClient] [Error]: Error while connecting with server.
MQTTnet.Exceptions.MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.
   at MQTTnet.PacketDispatcher.MqttPacketAwaiter`1.WaitOneAsync(TimeSpan timeout)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.AuthenticateAsync(IMqttChannelAdapter channelAdapter, MqttApplicationMessage willApplicationMessage, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
[2021-02-22T01:53:42.7665837Z] [] [4] [MqttClient] [Verbose]: Disconnecting [Timeout=00:00:10]
[2021-02-22T01:53:42.7667972Z] [] [4] [MqttClient] [Warning]: Error while disconnecting from adapter.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MqttChannelAdapter'.
   at MQTTnet.Internal.Disposable.ThrowIfDisposed()
   at MQTTnet.Adapter.MqttChannelAdapter.DisconnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.DisconnectInternalAsync(Task sender, Exception exception, MqttClientAuthenticateResult authenticateResult)
```
